<?php

declare(strict_types=1);

/**
 * Generates src/Matching/FlavourVocab.php: the seed flavour vocabulary built from the Vape and Go export
 * (pilot-1 fix 1, see Flavour::vocabularyFromSeed for the rule). Re-run when a new Vape and Go export is used:
 *
 *   nice -n 19 php -d memory_limit=2G tools/first_match/build_flavour_vocab.php [--vpg=<vapeandgo_listings_*.jsonl.gz>] [--stats=<json>]
 *
 * Read-only on the export; no database, no network. The generated words are PROPOSALS like every other seed
 * list in src/Matching: a mapping lead may prune them. tools/first_match/run.php records the vocabulary
 * version and warns when it was built from a different export than the one being matched.
 */

require __DIR__ . '/../../src/Matching/autoload.php';

use CW\Matching\Flavour;
use CW\Matching\Normalizer;

$opt = getopt('', ['vpg:', 'stats:']);
$base = '/root/cw_work/first_match';
$files = glob("$base/vapeandgo_listings_*.jsonl.gz") ?: [];
sort($files);
$vpgFile = $opt['vpg'] ?? (string) end($files);
if (!is_file($vpgFile)) {
    fwrite(STDERR, "no Vape and Go export\n");
    exit(2);
}
$rows = [];
$fh = gzopen($vpgFile, 'r');
while (($l = gzgets($fh)) !== false) {
    $l = trim($l);
    if ($l === '') {
        continue;
    }
    $r = json_decode($l, true, 512, JSON_BIGINT_AS_STRING | JSON_THROW_ON_ERROR);
    $rows[(int) $r['variant_id']] = $r;
}
gzclose($fh);
$sib = [];
foreach ($rows as $r) {
    if (($r['variant_status'] ?? '') === 'Published') {
        $sib[(int) $r['product_id']] = ($sib[(int) $r['product_id']] ?? 0) + 1;
    }
}
$seed = [];
foreach ($rows as $id => $r) {
    if (($r['variant_status'] ?? '') !== 'Published' || (int) $r['is_landing'] !== 0) {
        continue;
    }
    $f = Normalizer::normalize($r, ['published_siblings' => $sib[(int) $r['product_id']] ?? 0]);
    if (!$f['is_placeholder']) {
        $seed[] = $f;
    }
}
$v = Flavour::vocabularyFromSeed($seed);
$sha = hash_file('sha256', $vpgFile);
$words = $v['words'];
$lines = [];
$line = '       ';
foreach ($words as $w) {
    $piece = " '" . $w . "',";
    if (strlen($line) + strlen($piece) > 118) {
        $lines[] = $line;
        $line = '       ';
    }
    $line .= $piece;
}
$lines[] = $line;
$php = "<?php\n\ndeclare(strict_types=1);\n\nnamespace CW\\Matching;\n\n/**\n"
    . " * GENERATED by tools/first_match/build_flavour_vocab.php — do not edit by hand; re-run the tool instead.\n"
    . " *\n"
    . " * Seed flavour vocabulary from the Vape and Go export (pilot-1 fix 1; rule in Flavour::vocabularyFromSeed).\n"
    . " * Canonical (stemmed) tokens that name a flavour on more seed products than they name a line or brand, and are\n"
    . " * not already in Flavour::WORDS. PROPOSALS pending mapping-lead review, like every seed list here.\n"
    . " */\nfinal class FlavourVocab\n{\n"
    . "    public const VERSION = 'fv1-" . substr($sha, 0, 8) . "';\n\n"
    . "    public const SOURCE = [\n"
    . "        'file' => '" . basename($vpgFile) . "',\n"
    . "        'sha256' => '" . $sha . "',\n"
    . "        'seed_items' => " . count($seed) . ",\n"
    . "        'normalizer' => '" . Normalizer::VERSION . "',\n"
    . "        'words' => " . count($words) . ",\n"
    . "    ];\n\n"
    . "    public const WORDS = [\n" . implode("\n", $lines) . "\n    ];\n}\n";
$dest = __DIR__ . '/../../src/Matching/FlavourVocab.php';
file_put_contents($dest, $php);
if (isset($opt['stats'])) {
    file_put_contents($opt['stats'], json_encode($v['stats'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
}
echo json_encode(['wrote' => realpath($dest), 'words' => count($words), 'seed_items' => count($seed), 'source_sha256' => $sha]) . "\n";
