<?php

declare(strict_types=1);

/**
 * Plain test runner for src/Matching (no PHPUnit):  php tests/matching/run.php
 *
 * 1. Normaliser unit cases (synthetic rows).
 * 2. Gtin, Band and JudgeCard unit cases.
 * 3. Golden trap pairs taken from the real catalogue exports (tests/fixtures/matching/golden_listings.json,
 *    regenerated by tools/first_match/extract_fixture.php). Every trap must be VETOED or must NEVER band
 *    Key — even when a (simulated) judge agrees with confidence 100.
 * 4. True pairs that must NOT be vetoed (a false veto costs recall).
 */

require __DIR__ . '/../../src/Matching/autoload.php';

use CW\Matching\Band;
use CW\Matching\Candidates;
use CW\Matching\Flavour;
use CW\Matching\Gtin;
use CW\Matching\JudgeCard;
use CW\Matching\Normalizer;
use CW\Matching\Text;
use CW\Matching\Veto;

$pass = 0;
$fail = 0;
$failures = [];
function t(string $name, callable $fn): void
{
    global $pass, $fail, $failures;
    try {
        $fn();
        $pass++;
    } catch (Throwable $e) {
        $fail++;
        $failures[] = "FAIL $name: " . $e->getMessage();
    }
}
function ok(bool $c, string $msg = 'assertion failed'): void
{
    if (!$c) {
        throw new RuntimeException($msg);
    }
}
function eq(mixed $a, mixed $b, string $msg = ''): void
{
    if ($a !== $b) {
        throw new RuntimeException(($msg !== '' ? "$msg: " : '') . 'expected ' . json_encode($b) . ', got ' . json_encode($a));
    }
}
function row(array $o): array
{
    return $o + [
        'site' => 'test', 'variant_id' => 1, 'product_id' => 1, 'product_title' => '', 'variant_title' => '', 'brand' => '',
        'product_type' => 'simple', 'variant_status' => 'Published', 'is_landing' => 0, 'is_default' => 1, 'price' => 4.99,
        'sale_price' => null, 'barcodes' => [], 'attributes' => [], 'units_30d' => 0, 'units_365d' => 0,
    ];
}
function N(array $o, array $ctx = []): array
{
    return Normalizer::normalize(row($o), $ctx);
}
function attr(string $name, string $value, int $var = 0): array
{
    return ['attr_id' => 0, 'name' => $name, 'value' => $value, 'is_variable' => $var];
}
function codes(array $res): array
{
    return array_values(array_unique(array_column($res['vetoes'], 'code')));
}

// ───────────────────────────── fixture ─────────────────────────────
$fx = json_decode((string) file_get_contents(__DIR__ . '/../fixtures/matching/golden_listings.json'), true, 512, JSON_BIGINT_AS_STRING);
function F(string $site, int $id): array
{
    global $fx;
    $r = $fx['rows'][$site][(string) $id] ?? null;
    if ($r === null) {
        throw new RuntimeException("fixture missing $site#$id");
    }
    $f = Normalizer::normalize($r, $fx['ctx'][$site][(string) $id]);
    $f['product_live'] = ($r['product_status'] ?? '') === 'Published';
    return $f;
}
function A(int $id): array
{
    return F('electrofag', $id);
}
function V(int $id): array
{
    return F('vapeandgo', $id);
}
function R(string $site, int $id): array
{
    global $fx;
    return $fx['rows'][$site][(string) $id];
}
/** Veto a real ALT listing against a real VPG item (seed context taken from the fixture row). */
function pair(int $aid, int $vid): array
{
    $v = R('vapeandgo', $vid);
    $inSeed = ($v['variant_status'] ?? '') === 'Published' && (int) $v['is_landing'] === 0;
    return Veto::check(A($aid), V($vid), 1, ['s_in_seed' => $inSeed, 's_product_published' => ($v['product_status'] ?? '') === 'Published']);
}
/** Best band this pair can EVER reach as a barcode-lane pair, with a judge that agrees at confidence 100. */
function bestBand(int $aid, int $vid, string $lane = 'barcode'): string
{
    $res = pair($aid, $vid);
    $ev = ['lane' => $lane, 'target' => $vid, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'],
        'candidates' => [['id' => $vid, 'prescore' => 100, 'vetoes' => $res['vetoes']]]];
    return Band::final($ev, ['outcome' => 'match', 'chosen_id' => $vid, 'confidence' => 100, 'units_per_item' => 1])['band'];
}
function trap(int $aid, int $vid, string $expectVeto = null): void
{
    $res = pair($aid, $vid);
    if ($expectVeto !== null) {
        ok(in_array($expectVeto, codes($res), true), "A#$aid vs V#$vid: expected veto $expectVeto, got " . json_encode(codes($res)) . ' flags ' . json_encode($res['flags']));
    }
    $b = bestBand($aid, $vid);
    ok($b !== Band::KEY, "A#$aid vs V#$vid banded Key");
}
function truePair(int $aid, int $vid): array
{
    $res = pair($aid, $vid);
    ok($res['vetoes'] === [], "A#$aid vs V#$vid must not be vetoed, got " . json_encode($res['vetoes']));
    return $res;
}

// ═════════════════════════════ 1 Normaliser unit cases ═════════════════════════════
t('6K and 12K expand to puffs on devices', function () {
    $f = N(['product_title' => 'Hayati Pro Max Plus 6K Prefilled Pods', 'variant_title' => 'Blue Razz GB Hayati Pro Max Plus 6K Prefilled Pods - 5mg']);
    eq($f['puffs'], 6000, 'puffs');
    eq($f['line_numbers'], ['6000'], 'line numbers');
    eq($f['strength_mg'], 5.0, 'strength');
    eq($f['form'], 'prefilled_pod', 'form');
    $f = N(['variant_title' => 'Al Fakher 12k Pro Max Prefilled Pod Kit - Cold Blue']);
    eq($f['puffs'], 12000);
    eq($f['form'], 'pod_kit');
});
t('liquid line numbers are not puffs (Bar Juice 5000)', function () {
    $f = N(['variant_title' => 'Bar Juice 5000 Strawberry Kiwi 10ml Nic Salt E liquid - 20mg']);
    eq($f['puffs'], null);
    eq($f['line_numbers'], ['5000']);
    eq($f['form'], 'nic_salt');
    eq($f['nic_type'], 'salt');
    eq($f['volume_ml'], 10.0);
});
t('unknown pack is null, never 1 (product_mapping.php:146 bug)', function () {
    eq(N(['variant_title' => 'Lost Mary BM600 Prefilled Pod Kit - Cherry Ice'])['pack_units'], null);
    eq(N(['variant_title' => 'Vaporesso GTX Coils (Pack of 5) - 0.6 Ohm'])['pack_units'], 5);
    eq(N(['variant_title' => 'Innokin T18E Coils (5/pack) - 1.5 Ohm'])['pack_units'], 5);
    eq(N(['variant_title' => 'Aspire Pixo Replacement Pods', 'attributes' => [attr('Pack Size', '2 Pack')]])['pack_units'], 2);
    eq(N(['variant_title' => 'Smok Novo 2X Replacement Pod - Meshed 0.8 Ohm'])['pack_units'], null, 'Novo 2X is a model');
    eq(N(['variant_title' => 'Hayati X4 Refillable Replacement Pods (Pack of 3) - 0.6 Ohm'])['pack_units'], 3, 'X4 is a model');
});
t('"10 x 10ml" is a multiple: pack 10, 10ml each', function () {
    $f = N(['variant_title' => '10 x 10ml Nic Nic Nicotine Shots - 18mg/ml - 100% VG']);
    eq($f['pack_units'], 10);
    eq($f['listing_multiplier'], 10);
    eq($f['volume_ml'], 10.0);
    eq($f['strength_mg'], 18.0);
    eq($f['form'], 'nic_shot');
    eq($f['nic_type'], 'nic_shot');
});
t('strength parsing: mg, %, zero, is_variable wins, Choose an option dropped', function () {
    eq(N(['variant_title' => 'Some Salt 10ml Nic Salt - 1.8%'])['strength_mg'], 18.0);
    eq(N(['variant_title' => 'SKE Crystal Bar 600 Zero Nicotine Disposable - Fizzy Cherry'])['strength_mg'], 0.0);
    $f = N(['variant_title' => 'X Nic Salt 10ml', 'attributes' => [attr('Nicotine Strength', '10mg'), attr('Nicotine Strength', '20mg', 1), attr('Nicotine Strength', 'Choose an option')]]);
    eq($f['strength_mg'], 20.0);
    $f = N(['variant_title' => 'X Nic Salt 10ml', 'attributes' => [attr('Nicotine Strength', '10mg'), attr('Nicotine Strength', '20mg')]]);
    eq($f['strength_mg'], null, 'two values without a marker -> unknown');
    ok(in_array('strength', $f['conflict_fields'], true), 'internal conflict recorded');
    $f = N(['variant_title' => 'X Nic Salt 10ml - 10mg', 'attributes' => [attr('Nicotine Strength', '20mg', 1)]]);
    eq($f['strength_mg'], null, 'title vs attribute disagree -> unknown');
});
t('ALT attr "Strength" holding ohms becomes resistance', function () {
    $f = N(['variant_title' => 'Innokin T18E Coils (5/pack) - 1.5 Ohm', 'attributes' => [attr('Strength', '1.5 Ohm', 1)]]);
    eq($f['resistance_ohm'], 1.5);
    eq($f['strength_mg'], null);
    eq($f['form'], 'coil');
});
t('nic type: salt, freebase (title beats brand), shortfill, zero', function () {
    eq(N(['variant_title' => 'Strawberry Burst Freebase E-Liquid by Vampire Vape 10ml | 3mg', 'brand' => 'Vampire Vape Nic Salts'])['nic_type'], 'freebase');
    eq(N(['variant_title' => 'IVG Riberry Lemonade 10ml E Liquid - 3mg'])['nic_type'], 'freebase');
    eq(N(['variant_title' => 'Banana Ice Hayati Pro Max 100ml Shortfill Eliquid 70/30'])['nic_type'], 'shortfill');
    $f = N(['variant_title' => 'Hayati Pro Max Eliquid 70/30 - Banana Ice - 100ml', 'attributes' => [attr('Nicotine Strength', '0mg')]]);
    eq($f['form'], 'shortfill', '100ml 0mg e-liquid is a shortfill');
    eq($f['nic_type'], 'shortfill');
});
t('form classes', function () {
    $cases = [
        ['Lost Mary BM6000 Pod Kit - Pineapple Passionfruit | 20mg', 'pod_kit'],
        ['Pineapple Passionfruit Lost Mary BM6000 Refill Pack', 'prefilled_pod'],
        ['Vaporesso Xros Corex 2.0 Mesh Replacement Pod(Pack of 4) - 0.4ohm', 'refill_pod_cartridge'],
        ['Innokin Prism T18E, T22E Replacement Coils - 1.5 ohm', 'coil'],
        ['Innokin T18E Pro Tank | Coil Resistance : 1.7 Ohm - Black', 'tank'],
        ['Uwell Caliburn G3 Vape Kit - Black', 'kit'],
        ['Blueberry Sour Raspberry Juicy Pod Novamax 10K Vape Kit', 'pod_kit'],
        ['Icy Blackcurrant ZYN Nicotine Pouches 12.5mg', 'other'],
        ['IQOS Terea Tobacco - Pack Of 20 Sticks', 'other'],
        ['Kiwi & Cranberry On Ice 10ml 20mg Nicotine Salt E-Liquid by Just Juice', 'nic_salt'],
        ['Hayati Mini Ultra 1500 Puffs Prefilled Vape - Sour Apple', 'disposable'],
        ['Samsung 25R 18650 Battery', 'battery'],
    ];
    foreach ($cases as [$title, $form]) {
        eq(N(['variant_title' => $title])['form'], $form, $title);
    }
    $f = N(['variant_title' => 'Hayati Pro Ultra Plus Blackcurrant Cotton Candy / Blue Raspberry', 'attributes' => [attr('Puff Count', '25000')]]);
    ok($f['form'] !== 'accessory', 'cotton candy is a flavour, not an accessory');
    eq(N(['variant_title' => 'Oxva Xlim Refillable Pod Kit - Black'])['form_sub'], 'refillable');
    $f = N(['variant_title' => 'Lost Mary NERA 30K Fullview Refillable Pod Kit - Pineapple Edition']);
    eq($f['form_sub'], null, '"refillable" next to a 30K puff count contradicts itself');
    ok(in_array('form', $f['conflict_fields'], true));
    eq(N(['variant_title' => 'Lost Mary NERA 30K Fullview Prefilled Pod Kit - Pineapple Edition'])['form_sub'], 'prefilled');
});
t('line numbers after K expansion; modifiers', function () {
    eq(N(['variant_title' => 'Lost Mary BM600 Prefilled Pod Kit - Cherry Ice'])['line_numbers'], ['600']);
    eq(N(['variant_title' => 'Lost Mary BM6000 Prefilled Pod Kit - Cherry Ice'])['line_numbers'], ['6000']);
    eq(N(['variant_title' => 'Vaporesso Xros Corex 2.0 Mesh Replacement Pod(Pack of 4) - 0.4ohm'])['line_numbers'], ['2']);
    eq(N(['variant_title' => 'Lost Mary NERA 15K Prefilled Pods - Mint'])['line_numbers'], ['15000']);
    eq(N(['variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - Mr Blue'])['line_modifiers'], ['max', 'plus', 'pro']);
});
t('puff attribute typo (600 vs model 6000) is an internal conflict, not a value', function () {
    $f = N(['product_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit', 'variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - 20mg | Red Apple Ice',
        'attributes' => [attr('Puff Count', '600'), attr('Flavour', 'Red Apple Ice', 1)]]);
    eq($f['puffs'], null);
    ok(in_array('puffs', $f['conflict_fields'], true));
});
t('flavour: attr, l/I folding, entities, brackets', function () {
    $f = N(['product_title' => 'Crystal Pro CP 10K Pods', 'variant_title' => 'Blue Razz lce Crystal Pro CP 10K Pods']);
    ok(in_array('ice', $f['flavour_tokens'], true), 'lce -> ice');
    $f = N(['variant_title' => 'Kiwi &amp;amp; Cranberry on ice Nic Salt E liquid by Just Juice 10ml - 20mg']);
    eq($f['flavour_tokens'], ['kiwi', 'cranberry', 'ice']);
    $f = N(['variant_title' => 'Cotton Candy Ice (P&B Cloud) Nic Salt E-Liquid by Elf Bar Elfliq Salts 10ml - 5mg']);
    eq($f['flavour_tokens'], ['cotton', 'candy', 'ice']);
    ok(in_array('cloud', $f['paren_tokens'], true));
});
t('colour from attribute and from a device variant suffix', function () {
    eq(N(['variant_title' => 'Vaporesso Xros Pro Pod Kit - Red', 'attributes' => [attr('colour', 'Red', 1)]])['colour'], 'red');
    eq(N(['product_title' => 'Vaporesso Xros Pro Pod Vape Kit', 'variant_title' => 'Vaporesso Xros Pro Pod Vape Kit | Space Grey'])['colour'], 'space gray');
});
t('placeholder rule', function () {
    ok(N(['is_landing' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X Pods', 'product_type' => 'variable'])['is_placeholder']);
    ok(N(['is_landing' => 0, 'is_default' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X  pods', 'product_type' => 'variable'], ['published_siblings' => 3])['is_placeholder']);
    ok(!N(['is_landing' => 0, 'is_default' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X Pods', 'product_type' => 'variable', 'barcodes' => [5056168878109]], ['published_siblings' => 3])['is_placeholder']);
});

// ═════════════════════════════ 2 Gtin / Band / JudgeCard / Flavour units ═════════════════════════════
t('gtin check digit and keys', function () {
    ok(Gtin::checkDigitOk('5056168878109'));
    ok(!Gtin::checkDigitOk('5056168878108'));
    ok(Gtin::checkDigitOk('34966440488'), 'UPC-A with its leading zero dropped');
    eq(Gtin::key('06943498697557'), '6943498697557');
    eq(Gtin::key(6943498697557), '6943498697557');
    eq(Gtin::classify('1746')['usable'], false);
    eq(Gtin::classify('1746')['reason'], 'too_short');
    eq(Gtin::classify('5056168878108')['reason'], 'bad_check_digit');
    eq(Gtin::classify('5056168878109')['usable'], true);
    $idx = Gtin::index([1 => ['06943498697557'], 2 => [6943498697557], 3 => [5056168878109]]);
    ok(isset($idx['multi']['6943498697557']), 'same code on two items is flagged');
    ok(!isset($idx['multi']['5056168878109']));
});
t('band: provisional', function () {
    eq(Band::provisional(['lane' => 'ignore', 'is_placeholder' => true])['band'], Band::IGNORE);
    eq(Band::provisional(['lane' => 'barcode', 'flags' => ['multi_sku_gtin']])['band'], Band::CONFLICT);
    eq(Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [['code' => 'strength']]])['band'], Band::CONFLICT);
    $p = Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [], 'target_flags' => []]);
    eq([$p['band'], $p['ceiling']], [null, Band::KEY]);
    eq(Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [], 'target_flags' => ['price_outlier']])['ceiling'], Band::CHECK);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => []])['ceiling'], Band::NEW_ITEM);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 50, 'vetoes' => []]]])['ceiling'], Band::NEW_ITEM);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 80, 'vetoes' => []]], 'separating_field_missing' => 'strength'])['ceiling'], Band::CANT_TELL);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 80, 'vetoes' => []]]])['ceiling'], Band::CHECK);
});
t('band: final with a judge', function () {
    $key = ['lane' => 'barcode', 'target' => 7, 'target_vetoes' => [], 'target_flags' => [], 'candidates' => [['id' => 7, 'prescore' => 90, 'vetoes' => []], ['id' => 8, 'prescore' => 70, 'vetoes' => []]]];
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 95, 'units_per_item' => 1])['band'], Band::KEY);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 80, 'units_per_item' => 1])['band'], Band::CHECK);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 95, 'units_per_item' => 2])['band'], Band::CHECK);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 8, 'confidence' => 90, 'units_per_item' => 1])['band'], Band::CONFLICT);
    eq(Band::final($key, ['outcome' => 'no_match_in_list', 'chosen_id' => null, 'confidence' => 85, 'units_per_item' => null])['band'], Band::CONFLICT);
    eq(Band::final($key, ['outcome' => 'cannot_tell', 'chosen_id' => null, 'confidence' => 60, 'units_per_item' => null])['band'], Band::CANT_TELL);
    $open = ['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 50, 'vetoes' => []], ['id' => 2, 'prescore' => 95, 'vetoes' => [['code' => 'strength']]]]];
    eq(Band::final($open, ['outcome' => 'no_match_in_list', 'chosen_id' => null, 'confidence' => 95, 'units_per_item' => null])['band'], Band::NEW_ITEM);
    eq(Band::final($open, ['outcome' => 'match', 'chosen_id' => 2, 'confidence' => 99, 'units_per_item' => 1])['band'], Band::CONFLICT, 'AI match on a vetoed pair');
    eq(Band::final($open, ['outcome' => 'match', 'chosen_id' => 1, 'confidence' => 90, 'units_per_item' => 1])['band'], Band::CHECK, 'AI only is at most Check');
});
t('judge card is barcode-blind', function () {
    $r = R('electrofag', 7409);
    $f = A(7409);
    $c = JudgeCard::card('L1', $r, $f);
    eq(array_keys($c), JudgeCard::FIELDS);
    JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'listing' => $c]]], array_map('strval', $r['barcodes']));
    $threw = false;
    try {
        JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'listing' => $c + ['barcodes' => $r['barcodes']]]]], []);
    } catch (RuntimeException) {
        $threw = true;
    }
    ok($threw, 'a barcode field must be refused');
    eq(JudgeCard::mask('Code 5056168878109 inside'), 'Code [number] inside');
});
t('flavour helper', function () {
    ok(Flavour::same(['blue', 'razz', 'gb'], ['blue', 'razz', 'gummy', 'bear']));
    ok(Flavour::same(['bubble', 'gum', 'ice'], ['bubblegum', 'ice']));
    ok(!Flavour::same(['blue', 'razz'], ['blue', 'razz', 'lemonade']));
    eq(Flavour::compare(['blue', 'razz'], ['blue', 'razz', 'lemonade'], ['blue', 'razz'], ['blue', 'razz', 'lemonade'])['veto'], 'flavour_superset');
    eq(Flavour::compare(['caramel', 'tobacco'], ['cream', 'tobacco'], ['caramel', 'tobacco'], ['cream', 'tobacco'])['veto'], 'flavour_diff');
    eq(Flavour::compare(['deliciu'], ['strawberry', 'ice'], ['deliciu'], ['strawberry', 'ice', 'deliciu'])['veto'], null, 'an unstated flavour is never a superset');
});
t('veto: nic type alone (same strength)', function () {
    $a = N(['variant_title' => 'Brand X Cherry Freebase E-Liquid 10ml - 6mg']);
    $b = N(['variant_title' => 'Cherry Nic Salt E-Liquid by Brand X 10ml - 6mg']);
    eq(codes(Veto::check($a, $b)), ['nic_type']);
});
t('veto: pack uses listing.pack = item.pack x units', function () {
    $a = N(['variant_title' => 'Brand Y Coils (Pack of 5) - 0.6 Ohm']);
    $b = N(['variant_title' => 'Brand Y Coils (Pack of 5) - 0.6 Ohm']);
    $c = N(['variant_title' => 'Brand Y Coils (Pack of 3) - 0.6 Ohm']);
    eq(codes(Veto::check($a, $b, 1)), []);
    eq(codes(Veto::check($a, $c, 1)), ['pack']);
    eq(codes(Veto::check($a, $b, 2)), ['pack'], 'u=2 on a 5-pack needs a 10-pack listing');
});

// ═════════════════════════════ 3 golden traps from the real exports ═════════════════════════════
t('trap: strength sibling (A#1628 10mg vs VPG 20mg sibling)', fn () => trap(1628, 8554, 'strength'));
t('trap: salt vs freebase (A#4771 3mg e-liquid vs IVG Intense nic salt)', function () {
    trap(4771, 37640, 'nic_type');
    trap(4774, 37640, 'nic_type');   // 18mg e-liquid vs 20mg salt: also strength
    ok(in_array('strength', codes(pair(4774, 37640)), true));
});
t('trap: Bar vs Bar Plus (Hayati Pro Ultra Plus vs Pro Ultra; Elf Bar vs Elf Bar Plus 15)', function () {
    trap(3648, 30201, 'line_modifier');
    trap(2031, 42870, 'line_modifier');
});
t('trap: 600 vs 6000 (Lost Mary BM600 vs BM6000, same flavour)', fn () => trap(5302, 32108, 'line_number'));
t('trap: Corex 2.0 vs 3.0 (same ohm, same pack)', function () {
    trap(9408, 41615, 'line_number');
    trap(9414, 31810, 'line_number');
});
t('trap: kit vs refill (A#5387 BM6000 kit vs refill pack; Gold Bar reload pods vs kit)', function () {
    trap(5387, 43443, 'form');
    trap(2984, 31162, 'form');
});
t('trap: flavour superset (Blueberry Raspberry vs Blueberry Raspberry Lemonade; Peach Mango vs Peach Mango Ice)', function () {
    trap(6840, 36530, 'flavour_superset');
    trap(4026, 40543, 'flavour_superset');
});
t('trap: flavour difference (A#1032 Caramel vs Cream Tobacco; A#1345 Juicy Raspberries vs Juicy Peach)', function () {
    trap(1032, 13420, 'flavour_diff');
    trap(1345, 40078, 'flavour_diff');
});
t('trap: "10 x 10ml" multiple is never Key against the single or the multiple', function () {
    trap(6067, 51);
    $res = pair(6067, 51);
    ok(in_array('listing_multiplier', $res['flags'], true), 'listing_multiplier flag');
    ok(in_array('price_outlier', $res['flags'], true), 'price outlier flag');
});
t('trap: relabelled line (ALT Crystal Pro Max vs VPG Hayati Pro Max, shared barcode) never Key', function () {
    trap(8182, 28198);
    ok(in_array('relabelled_line_unconfirmed', pair(8182, 28198)['flags'], true));
});
t('trap: distributor brand ("Vapes Bars" selling PIXL) is blocked by title family, not aliased 1:1', function () {
    $a = A(6597);
    eq($a['brand_family'], ['bars']);
    $res = truePair(6597, 37353);
    eq($res['fields']['brand_line'], 'agree', 'brand/line agrees through the title');
    $seed = [37353 => V(37353), 28198 => V(28198)];
    $c = new Candidates($seed, []);
    ok(in_array('pixl', $c->blockFamilies($a), true), 'title family word blocks');
    ok(in_array(37353, array_column($c->generate($a), 'id'), true), 'true item is a candidate');
});
t('trap: two-EAN listing hitting two items (A#7409 SKE 600 Pro 1-pack vs 2-pack) is multi_sku_gtin', function () {
    $idx = Gtin::index([38563 => R('vapeandgo', 38563)['barcodes'], 36279 => R('vapeandgo', 36279)['barcodes']]);
    $hits = [];
    foreach (Gtin::listingKeys(R('electrofag', 7409)['barcodes'])['usable'] as $k) {
        foreach ($idx['by_key'][$k] ?? [] as $id) {
            $hits[$id] = true;
        }
    }
    eq(count($hits), 2);
    eq(Band::provisional(['lane' => 'barcode', 'flags' => ['multi_sku_gtin']])['band'], Band::CONFLICT);
    $v = Veto::check(V(38563), V(36279));
    ok(in_array('pack', codes($v), true), '1-pack vs 2-pack');
});
t('trap: shared VPG barcode on Corex 2.0 and 3.0 is not usable', function () {
    $idx = Gtin::index([31810 => R('vapeandgo', 31810)['barcodes'], 41615 => R('vapeandgo', 41615)['barcodes']]);
    ok(isset($idx['multi']['6943498697557']));
});
t('trap: placeholder decoy (A#30 vs the VPG parent row) and landing listing A#461', function () {
    ok(in_array('placeholder', codes(pair(30, 40391)), true));
    truePair(30, 40378);
    ok(A(461)['is_placeholder']);
    eq(Band::provisional(['lane' => 'ignore', 'is_placeholder' => true])['band'], Band::IGNORE);
});
t('trap: strength missing among strength siblings is never Key', function () {
    $a = N(['variant_title' => 'Banana Kiwi Ice Riot Squad BAR EDTN 10ml Nic Salt E Liquid', 'brand' => 'Riot Squad']);
    $s = V(12938);
    $res = Veto::check($a, $s, 1, ['s_strength_sibling' => true]);
    ok(in_array('strength_missing', $res['flags'], true));
    $ev = ['lane' => 'barcode', 'target' => 12938, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    ok(Band::final($ev, ['outcome' => 'match', 'chosen_id' => 12938, 'confidence' => 100, 'units_per_item' => 1])['band'] !== Band::KEY);
});
t('trap: barcode and transfer disagree (A#3648) is a Conflict', function () {
    eq(Band::provisional(['lane' => 'barcode', 'target' => 36645, 'flags' => ['barcode_transfer_disagree']])['band'], Band::CONFLICT);
});

// ═════════════════════════════ 4 true pairs that must not be vetoed ═════════════════════════════
t('true pairs (barcode pairs, naming noise only) are not vetoed', function () {
    foreach ([[7531, 38228], [3308, 33157], [10952, 45513], [886, 38916], [9403, 29794], [4877, 44970], [3249, 29380],
        [6294, 34922], [9347, 37053], [9577, 11714], [2215, 30477], [1628, 8553], [4280, 847], [3648, 36645], [6067, 48]] as [$a, $v]) {
        truePair($a, $v);
    }
});
t('ALT puff attribute error (600 on a 6000 device) does not veto, but blocks Key', function () {
    $res = truePair(11850, 45768);
    ok(in_array('internal_conflict', $res['flags'], true));
    ok(bestBand(11850, 45768) !== Band::KEY);
});
t('"Refillable" printed next to a flavour is a data conflict, not a form veto', function () {
    $res = truePair(5396, 37097);
    ok(in_array('internal_conflict', $res['flags'], true));
});
t('a clean barcode pair can reach Key only with the judge', function () {
    eq(bestBand(7531, 38228), Band::KEY);
    $res = pair(7531, 38228);
    $ev = ['lane' => 'barcode', 'target' => 38228, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    eq(Band::provisional($ev)['band'], null, 'no band without the judge');
    eq(Band::provisional($ev)['ceiling'], Band::KEY);
});

// ─────────────────────────────
foreach ($failures as $f) {
    fwrite(STDERR, $f . "\n");
}
echo json_encode(['passed' => $pass, 'failed' => $fail]) . "\n";
exit($fail === 0 ? 0 : 1);
