<?php

declare(strict_types=1);

/**
 * Plain test runner for src/Matching (no PHPUnit):  php tests/matching/run.php
 *
 * 1. Normaliser unit cases (synthetic rows).
 * 2. Gtin, Band and JudgeCard unit cases.
 * 3. Golden trap pairs taken from the real catalogue exports (tests/fixtures/matching/golden_listings.json,
 *    regenerated by tools/first_match/extract_fixture.php). Every trap must be VETOED or must NEVER band
 *    Key — even when a (simulated) judge agrees with confidence 100.
 * 4. True pairs that must NOT be vetoed (a false veto costs recall).
 * 5. Regression cases for every pilot-1 miss (run1 pilot_eval): each trap is vetoed or soft-flagged so it can
 *    never reach Key, and each true counterpart stays clean.
 * 6. The run3 follow-ups (docs/decisions.md M29): (a) Riot Squad "BAR EDTN" XL false line_modifier veto, (b) "B Gum" =
 *    Bubblegum, (c) one scratch directory per judge, (d) one form enum, (e) Band's key-lane no-match label.
 */

require __DIR__ . '/../../src/Matching/autoload.php';

use CW\Matching\Band;
use CW\Matching\Candidates;
use CW\Matching\Flavour;
use CW\Matching\Form;
use CW\Matching\Gtin;
use CW\Matching\JudgeCard;
use CW\Matching\JudgeScratch;
use CW\Matching\Normalizer;
use CW\Matching\StoredBand;
use CW\Matching\Text;
use CW\Matching\TitlePattern;
use CW\Matching\Veto;

$pass = 0;
$fail = 0;
$failures = [];
function t(string $name, callable $fn): void
{
    global $pass, $fail, $failures;
    try {
        $fn();
        $pass++;
    } catch (Throwable $e) {
        $fail++;
        $failures[] = "FAIL $name: " . $e->getMessage();
    }
}
function ok(bool $c, string $msg = 'assertion failed'): void
{
    if (!$c) {
        throw new RuntimeException($msg);
    }
}
function eq(mixed $a, mixed $b, string $msg = ''): void
{
    if ($a !== $b) {
        throw new RuntimeException(($msg !== '' ? "$msg: " : '') . 'expected ' . json_encode($b) . ', got ' . json_encode($a));
    }
}
function row(array $o): array
{
    return $o + [
        'site' => 'test', 'variant_id' => 1, 'product_id' => 1, 'product_title' => '', 'variant_title' => '', 'brand' => '',
        'product_type' => 'simple', 'variant_status' => 'Published', 'is_landing' => 0, 'is_default' => 1, 'price' => 4.99,
        'sale_price' => null, 'barcodes' => [], 'attributes' => [], 'units_30d' => 0, 'units_365d' => 0,
    ];
}
function N(array $o, array $ctx = []): array
{
    return Normalizer::normalize(row($o), $ctx);
}
function attr(string $name, string $value, int $var = 0): array
{
    return ['attr_id' => 0, 'name' => $name, 'value' => $value, 'is_variable' => $var];
}
function codes(array $res): array
{
    return array_values(array_unique(array_column($res['vetoes'], 'code')));
}

// ───────────────────────────── fixture ─────────────────────────────
$fx = json_decode((string) file_get_contents(__DIR__ . '/../fixtures/matching/golden_listings.json'), true, 512, JSON_BIGINT_AS_STRING);
function F(string $site, int $id): array
{
    global $fx;
    $r = $fx['rows'][$site][(string) $id] ?? null;
    if ($r === null) {
        throw new RuntimeException("fixture missing $site#$id");
    }
    $f = Normalizer::normalize($r, $fx['ctx'][$site][(string) $id]);
    $f['product_live'] = ($r['product_status'] ?? '') === 'Published';
    return $f;
}
function A(int $id): array
{
    return F('electrofag', $id);
}
function V(int $id): array
{
    return F('vapeandgo', $id);
}
function R(string $site, int $id): array
{
    global $fx;
    return $fx['rows'][$site][(string) $id];
}
/** Veto a real ALT listing against a real VPG item (seed context taken from the fixture row). */
function pair(int $aid, int $vid): array
{
    $v = R('vapeandgo', $vid);
    $inSeed = ($v['variant_status'] ?? '') === 'Published' && (int) $v['is_landing'] === 0;
    return Veto::check(A($aid), V($vid), 1, ['s_in_seed' => $inSeed, 's_product_published' => ($v['product_status'] ?? '') === 'Published']);
}
/** Best band this pair can EVER reach as a barcode-lane pair, with a judge that agrees at confidence 100. */
function bestBand(int $aid, int $vid, string $lane = 'barcode'): string
{
    $res = pair($aid, $vid);
    $ev = ['lane' => $lane, 'target' => $vid, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'],
        'candidates' => [['id' => $vid, 'prescore' => 100, 'vetoes' => $res['vetoes']]]];
    return Band::final($ev, ['outcome' => 'match', 'chosen_id' => $vid, 'confidence' => 100, 'units_per_item' => 1])['band'];
}
function trap(int $aid, int $vid, string $expectVeto = null): void
{
    $res = pair($aid, $vid);
    if ($expectVeto !== null) {
        ok(in_array($expectVeto, codes($res), true), "A#$aid vs V#$vid: expected veto $expectVeto, got " . json_encode(codes($res)) . ' flags ' . json_encode($res['flags']));
    }
    $b = bestBand($aid, $vid);
    ok($b !== Band::KEY, "A#$aid vs V#$vid banded Key");
}
function truePair(int $aid, int $vid): array
{
    $res = pair($aid, $vid);
    ok($res['vetoes'] === [], "A#$aid vs V#$vid must not be vetoed, got " . json_encode($res['vetoes']));
    return $res;
}

// ═════════════════════════════ 1 Normaliser unit cases ═════════════════════════════
t('6K and 12K expand to puffs on devices', function () {
    $f = N(['product_title' => 'Hayati Pro Max Plus 6K Prefilled Pods', 'variant_title' => 'Blue Razz GB Hayati Pro Max Plus 6K Prefilled Pods - 5mg']);
    eq($f['puffs'], 6000, 'puffs');
    eq($f['line_numbers'], ['6000'], 'line numbers');
    eq($f['strength_mg'], 5.0, 'strength');
    eq($f['form'], 'prefilled_pod', 'form');
    $f = N(['variant_title' => 'Al Fakher 12k Pro Max Prefilled Pod Kit - Cold Blue']);
    eq($f['puffs'], 12000);
    eq($f['form'], 'pod_kit');
});
t('liquid line numbers are not puffs (Bar Juice 5000)', function () {
    $f = N(['variant_title' => 'Bar Juice 5000 Strawberry Kiwi 10ml Nic Salt E liquid - 20mg']);
    eq($f['puffs'], null);
    eq($f['line_numbers'], ['5000']);
    eq($f['form'], 'nic_salt');
    eq($f['nic_type'], 'salt');
    eq($f['volume_ml'], 10.0);
});
t('unknown pack is null, never 1 (product_mapping.php:146 bug)', function () {
    eq(N(['variant_title' => 'Lost Mary BM600 Prefilled Pod Kit - Cherry Ice'])['pack_units'], null);
    eq(N(['variant_title' => 'Vaporesso GTX Coils (Pack of 5) - 0.6 Ohm'])['pack_units'], 5);
    eq(N(['variant_title' => 'Innokin T18E Coils (5/pack) - 1.5 Ohm'])['pack_units'], 5);
    eq(N(['variant_title' => 'Aspire Pixo Replacement Pods', 'attributes' => [attr('Pack Size', '2 Pack')]])['pack_units'], 2);
    eq(N(['variant_title' => 'Smok Novo 2X Replacement Pod - Meshed 0.8 Ohm'])['pack_units'], null, 'Novo 2X is a model');
    eq(N(['variant_title' => 'Hayati X4 Refillable Replacement Pods (Pack of 3) - 0.6 Ohm'])['pack_units'], 3, 'X4 is a model');
});
t('"10 x 10ml" is a multiple: pack 10, 10ml each', function () {
    $f = N(['variant_title' => '10 x 10ml Nic Nic Nicotine Shots - 18mg/ml - 100% VG']);
    eq($f['pack_units'], 10);
    eq($f['listing_multiplier'], 10);
    eq($f['volume_ml'], 10.0);
    eq($f['strength_mg'], 18.0);
    eq($f['form'], 'nic_shot');
    eq($f['nic_type'], 'nic_shot');
});
t('strength parsing: mg, %, zero, is_variable wins, Choose an option dropped', function () {
    eq(N(['variant_title' => 'Some Salt 10ml Nic Salt - 1.8%'])['strength_mg'], 18.0);
    eq(N(['variant_title' => 'SKE Crystal Bar 600 Zero Nicotine Disposable - Fizzy Cherry'])['strength_mg'], 0.0);
    $f = N(['variant_title' => 'X Nic Salt 10ml', 'attributes' => [attr('Nicotine Strength', '10mg'), attr('Nicotine Strength', '20mg', 1), attr('Nicotine Strength', 'Choose an option')]]);
    eq($f['strength_mg'], 20.0);
    $f = N(['variant_title' => 'X Nic Salt 10ml', 'attributes' => [attr('Nicotine Strength', '10mg'), attr('Nicotine Strength', '20mg')]]);
    eq($f['strength_mg'], null, 'two values without a marker -> unknown');
    ok(in_array('strength', $f['conflict_fields'], true), 'internal conflict recorded');
    $f = N(['variant_title' => 'X Nic Salt 10ml - 10mg', 'attributes' => [attr('Nicotine Strength', '20mg', 1)]]);
    eq($f['strength_mg'], null, 'title vs attribute disagree -> unknown');
});
t('ALT attr "Strength" holding ohms becomes resistance', function () {
    $f = N(['variant_title' => 'Innokin T18E Coils (5/pack) - 1.5 Ohm', 'attributes' => [attr('Strength', '1.5 Ohm', 1)]]);
    eq($f['resistance_ohm'], 1.5);
    eq($f['strength_mg'], null);
    eq($f['form'], 'coil');
});
t('nic type: salt, freebase (title beats brand), shortfill, zero', function () {
    eq(N(['variant_title' => 'Strawberry Burst Freebase E-Liquid by Vampire Vape 10ml | 3mg', 'brand' => 'Vampire Vape Nic Salts'])['nic_type'], 'freebase');
    eq(N(['variant_title' => 'IVG Riberry Lemonade 10ml E Liquid - 3mg'])['nic_type'], 'freebase');
    eq(N(['variant_title' => 'Banana Ice Hayati Pro Max 100ml Shortfill Eliquid 70/30'])['nic_type'], 'shortfill');
    $f = N(['variant_title' => 'Hayati Pro Max Eliquid 70/30 - Banana Ice - 100ml', 'attributes' => [attr('Nicotine Strength', '0mg')]]);
    eq($f['form'], 'shortfill', '100ml 0mg e-liquid is a shortfill');
    eq($f['nic_type'], 'shortfill');
});
t('form classes', function () {
    $cases = [
        ['Lost Mary BM6000 Pod Kit - Pineapple Passionfruit | 20mg', 'pod_kit'],
        ['Pineapple Passionfruit Lost Mary BM6000 Refill Pack', 'prefilled_pod'],
        ['Vaporesso Xros Corex 2.0 Mesh Replacement Pod(Pack of 4) - 0.4ohm', 'refill_pod_cartridge'],
        ['Innokin Prism T18E, T22E Replacement Coils - 1.5 ohm', 'coil'],
        ['Innokin T18E Pro Tank | Coil Resistance : 1.7 Ohm - Black', 'tank'],
        ['Uwell Caliburn G3 Vape Kit - Black', 'kit'],
        ['Blueberry Sour Raspberry Juicy Pod Novamax 10K Vape Kit', 'pod_kit'],
        ['Icy Blackcurrant ZYN Nicotine Pouches 12.5mg', 'other'],
        ['IQOS Terea Tobacco - Pack Of 20 Sticks', 'other'],
        ['Kiwi & Cranberry On Ice 10ml 20mg Nicotine Salt E-Liquid by Just Juice', 'nic_salt'],
        ['Hayati Mini Ultra 1500 Puffs Prefilled Vape - Sour Apple', 'disposable'],
        ['Samsung 25R 18650 Battery', 'battery'],
    ];
    foreach ($cases as [$title, $form]) {
        eq(N(['variant_title' => $title])['form'], $form, $title);
    }
    $f = N(['variant_title' => 'Hayati Pro Ultra Plus Blackcurrant Cotton Candy / Blue Raspberry', 'attributes' => [attr('Puff Count', '25000')]]);
    ok($f['form'] !== 'accessory', 'cotton candy is a flavour, not an accessory');
    eq(N(['variant_title' => 'Oxva Xlim Refillable Pod Kit - Black'])['form_sub'], 'refillable');
    $f = N(['variant_title' => 'Lost Mary NERA 30K Fullview Refillable Pod Kit - Pineapple Edition']);
    eq($f['form_sub'], null, '"refillable" next to a 30K puff count contradicts itself');
    ok(in_array('form', $f['conflict_fields'], true));
    eq(N(['variant_title' => 'Lost Mary NERA 30K Fullview Prefilled Pod Kit - Pineapple Edition'])['form_sub'], 'prefilled');
});
t('line numbers after K expansion; modifiers', function () {
    eq(N(['variant_title' => 'Lost Mary BM600 Prefilled Pod Kit - Cherry Ice'])['line_numbers'], ['600']);
    eq(N(['variant_title' => 'Lost Mary BM6000 Prefilled Pod Kit - Cherry Ice'])['line_numbers'], ['6000']);
    eq(N(['variant_title' => 'Vaporesso Xros Corex 2.0 Mesh Replacement Pod(Pack of 4) - 0.4ohm'])['line_numbers'], ['2']);
    eq(N(['variant_title' => 'Lost Mary NERA 15K Prefilled Pods - Mint'])['line_numbers'], ['15000']);
    eq(N(['variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - Mr Blue'])['line_modifiers'], ['max', 'plus', 'pro']);
});
t('puff attribute typo (600 vs model 6000) is an internal conflict, not a value', function () {
    $f = N(['product_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit', 'variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - 20mg | Red Apple Ice',
        'attributes' => [attr('Puff Count', '600'), attr('Flavour', 'Red Apple Ice', 1)]]);
    eq($f['puffs'], null);
    ok(in_array('puffs', $f['conflict_fields'], true));
});
t('flavour: attr, l/I folding, entities, brackets', function () {
    $f = N(['product_title' => 'Crystal Pro CP 10K Pods', 'variant_title' => 'Blue Razz lce Crystal Pro CP 10K Pods']);
    ok(in_array('ice', $f['flavour_tokens'], true), 'lce -> ice');
    $f = N(['variant_title' => 'Kiwi &amp;amp; Cranberry on ice Nic Salt E liquid by Just Juice 10ml - 20mg']);
    eq($f['flavour_tokens'], ['kiwi', 'cranberry', 'ice']);
    $f = N(['variant_title' => 'Cotton Candy Ice (P&B Cloud) Nic Salt E-Liquid by Elf Bar Elfliq Salts 10ml - 5mg']);
    eq($f['flavour_tokens'], ['cotton', 'candy', 'ice']);
    ok(in_array('cloud', $f['paren_tokens'], true));
});
t('colour from attribute and from a device variant suffix', function () {
    eq(N(['variant_title' => 'Vaporesso Xros Pro Pod Kit - Red', 'attributes' => [attr('colour', 'Red', 1)]])['colour'], 'red');
    eq(N(['product_title' => 'Vaporesso Xros Pro Pod Vape Kit', 'variant_title' => 'Vaporesso Xros Pro Pod Vape Kit | Space Grey'])['colour'], 'space gray');
});
t('placeholder rule', function () {
    ok(N(['is_landing' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X Pods', 'product_type' => 'variable'])['is_placeholder']);
    ok(N(['is_landing' => 0, 'is_default' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X  pods', 'product_type' => 'variable'], ['published_siblings' => 3])['is_placeholder']);
    ok(!N(['is_landing' => 0, 'is_default' => 1, 'variant_title' => 'X Pods', 'product_title' => 'X Pods', 'product_type' => 'variable', 'barcodes' => [5056168878109]], ['published_siblings' => 3])['is_placeholder']);
});

// ═════════════════════════════ 2 Gtin / Band / JudgeCard / Flavour units ═════════════════════════════
t('gtin check digit and keys', function () {
    ok(Gtin::checkDigitOk('5056168878109'));
    ok(!Gtin::checkDigitOk('5056168878108'));
    ok(Gtin::checkDigitOk('34966440488'), 'UPC-A with its leading zero dropped');
    eq(Gtin::key('06943498697557'), '6943498697557');
    eq(Gtin::key(6943498697557), '6943498697557');
    eq(Gtin::classify('1746')['usable'], false);
    eq(Gtin::classify('1746')['reason'], 'too_short');
    eq(Gtin::classify('5056168878108')['reason'], 'bad_check_digit');
    eq(Gtin::classify('5056168878109')['usable'], true);
    $idx = Gtin::index([1 => ['06943498697557'], 2 => [6943498697557], 3 => [5056168878109]]);
    ok(isset($idx['multi']['6943498697557']), 'same code on two items is flagged');
    ok(!isset($idx['multi']['5056168878109']));
});
t('band: provisional', function () {
    eq(Band::provisional(['lane' => 'ignore', 'is_placeholder' => true])['band'], Band::IGNORE);
    eq(Band::provisional(['lane' => 'barcode', 'flags' => ['multi_sku_gtin']])['band'], Band::CONFLICT);
    eq(Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [['code' => 'strength']]])['band'], Band::CONFLICT);
    $p = Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [], 'target_flags' => []]);
    eq([$p['band'], $p['ceiling']], [null, Band::KEY]);
    eq(Band::provisional(['lane' => 'barcode', 'target' => 5, 'target_vetoes' => [], 'target_flags' => ['price_outlier']])['ceiling'], Band::CHECK);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => []])['ceiling'], Band::NEW_ITEM);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 50, 'vetoes' => []]]])['ceiling'], Band::NEW_ITEM);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 80, 'vetoes' => []]], 'separating_field_missing' => 'strength'])['ceiling'], Band::CANT_TELL);
    eq(Band::provisional(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 80, 'vetoes' => []]]])['ceiling'], Band::CHECK);
});
t('band: final with a judge', function () {
    $key = ['lane' => 'barcode', 'target' => 7, 'target_vetoes' => [], 'target_flags' => [], 'candidates' => [['id' => 7, 'prescore' => 90, 'vetoes' => []], ['id' => 8, 'prescore' => 70, 'vetoes' => []]]];
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 95, 'units_per_item' => 1])['band'], Band::KEY);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 80, 'units_per_item' => 1])['band'], Band::CHECK);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 95, 'units_per_item' => 2])['band'], Band::CHECK);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 8, 'confidence' => 90, 'units_per_item' => 1])['band'], Band::CONFLICT);
    eq(Band::final($key, ['outcome' => 'no_match_in_list', 'chosen_id' => null, 'confidence' => 85, 'units_per_item' => null])['band'], Band::CONFLICT);
    eq(Band::final($key, ['outcome' => 'cannot_tell', 'chosen_id' => null, 'confidence' => 60, 'units_per_item' => null])['band'], Band::CANT_TELL);
    $open = ['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 50, 'vetoes' => []], ['id' => 2, 'prescore' => 95, 'vetoes' => [['code' => 'strength']]]]];
    eq(Band::final($open, ['outcome' => 'no_match_in_list', 'chosen_id' => null, 'confidence' => 95, 'units_per_item' => null])['band'], Band::NEW_ITEM);
    eq(Band::final($open, ['outcome' => 'match', 'chosen_id' => 2, 'confidence' => 99, 'units_per_item' => 1])['band'], Band::CONFLICT, 'AI match on a vetoed pair');
    eq(Band::final($open, ['outcome' => 'match', 'chosen_id' => 1, 'confidence' => 90, 'units_per_item' => 1])['band'], Band::CHECK, 'AI only is at most Check');
});
t('judge card is barcode-blind', function () {
    $r = R('electrofag', 7409);
    $f = A(7409);
    $c = JudgeCard::card('L1', $r, $f);
    eq(array_keys($c), JudgeCard::CORE_FIELDS);
    JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'listing' => $c]]], array_map('strval', $r['barcodes']));
    $threw = false;
    try {
        JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'listing' => $c + ['barcodes' => $r['barcodes']]]]], []);
    } catch (RuntimeException) {
        $threw = true;
    }
    ok($threw, 'a barcode field must be refused');
    eq(JudgeCard::mask('Code 5056168878109 inside'), 'Code [number] inside');
});
t('flavour helper', function () {
    ok(Flavour::same(['blue', 'razz', 'gb'], ['blue', 'razz', 'gummy', 'bear']));
    ok(Flavour::same(['bubble', 'gum', 'ice'], ['bubblegum', 'ice']));
    ok(!Flavour::same(['blue', 'razz'], ['blue', 'razz', 'lemonade']));
    eq(Flavour::compare(['blue', 'razz'], ['blue', 'razz', 'lemonade'], ['blue', 'razz'], ['blue', 'razz', 'lemonade'])['veto'], 'flavour_superset');
    eq(Flavour::compare(['caramel', 'tobacco'], ['cream', 'tobacco'], ['caramel', 'tobacco'], ['cream', 'tobacco'])['veto'], 'flavour_diff');
    eq(Flavour::compare(['deliciu'], ['strawberry', 'ice'], ['deliciu'], ['strawberry', 'ice', 'deliciu'])['veto'], null, 'an unstated flavour is never a superset');
});
t('veto: nic type alone (same strength)', function () {
    $a = N(['variant_title' => 'Brand X Cherry Freebase E-Liquid 10ml - 6mg']);
    $b = N(['variant_title' => 'Cherry Nic Salt E-Liquid by Brand X 10ml - 6mg']);
    eq(codes(Veto::check($a, $b)), ['nic_type']);
});
t('veto: pack uses listing.pack = item.pack x units', function () {
    $a = N(['variant_title' => 'Brand Y Coils (Pack of 5) - 0.6 Ohm']);
    $b = N(['variant_title' => 'Brand Y Coils (Pack of 5) - 0.6 Ohm']);
    $c = N(['variant_title' => 'Brand Y Coils (Pack of 3) - 0.6 Ohm']);
    eq(codes(Veto::check($a, $b, 1)), []);
    eq(codes(Veto::check($a, $c, 1)), ['pack']);
    eq(codes(Veto::check($a, $b, 2)), ['pack'], 'u=2 on a 5-pack needs a 10-pack listing');
});

// ═════════════════════════════ 3 golden traps from the real exports ═════════════════════════════
t('trap: strength sibling (A#1628 10mg vs VPG 20mg sibling)', fn () => trap(1628, 8554, 'strength'));
t('trap: salt vs freebase (A#4771 3mg e-liquid vs IVG Intense nic salt)', function () {
    trap(4771, 37640, 'nic_type');
    trap(4774, 37640, 'nic_type');   // 18mg e-liquid vs 20mg salt: also strength
    ok(in_array('strength', codes(pair(4774, 37640)), true));
});
t('trap: Bar vs Bar Plus (Hayati Pro Ultra Plus vs Pro Ultra; Elf Bar vs Elf Bar Plus 15)', function () {
    trap(3648, 30201, 'line_modifier');
    trap(2031, 42870, 'line_modifier');
});
t('trap: 600 vs 6000 (Lost Mary BM600 vs BM6000, same flavour)', fn () => trap(5302, 32108, 'line_number'));
t('trap: Corex 2.0 vs 3.0 (same ohm, same pack)', function () {
    trap(9408, 41615, 'line_number');
    trap(9414, 31810, 'line_number');
});
t('trap: kit vs refill (A#5387 BM6000 kit vs refill pack; Gold Bar reload pods vs kit)', function () {
    trap(5387, 43443, 'form');
    trap(2984, 31162, 'form');
});
t('trap: flavour superset (Blueberry Raspberry vs Blueberry Raspberry Lemonade; Peach Mango vs Peach Mango Ice)', function () {
    trap(6840, 36530, 'flavour_superset');
    trap(4026, 40543, 'flavour_superset');
});
t('trap: flavour difference (A#1032 Caramel vs Cream Tobacco; A#1345 Juicy Raspberries vs Juicy Peach)', function () {
    trap(1032, 13420, 'flavour_diff');
    trap(1345, 40078, 'flavour_diff');
});
t('trap: "10 x 10ml" multiple is never Key against the single or the multiple', function () {
    trap(6067, 51);
    $res = pair(6067, 51);
    ok(in_array('listing_multiplier', $res['flags'], true), 'listing_multiplier flag');
    ok(in_array('price_outlier', $res['flags'], true), 'price outlier flag');
});
t('trap: relabelled line (ALT Crystal Pro Max vs VPG Hayati Pro Max, shared barcode) never Key', function () {
    trap(8182, 28198);
    ok(in_array('relabelled_line_unconfirmed', pair(8182, 28198)['flags'], true));
});
t('trap: distributor brand ("Vapes Bars" selling PIXL) is blocked by title family, not aliased 1:1', function () {
    $a = A(6597);
    eq($a['brand_family'], ['bars']);
    $res = truePair(6597, 37353);
    eq($res['fields']['brand_line'], 'agree', 'brand/line agrees through the title');
    $seed = [37353 => V(37353), 28198 => V(28198)];
    $c = new Candidates($seed, []);
    ok(in_array('pixl', $c->blockFamilies($a), true), 'title family word blocks');
    ok(in_array(37353, array_column($c->generate($a), 'id'), true), 'true item is a candidate');
});
t('trap: two-EAN listing hitting two items (A#7409 SKE 600 Pro 1-pack vs 2-pack) is multi_sku_gtin', function () {
    $idx = Gtin::index([38563 => R('vapeandgo', 38563)['barcodes'], 36279 => R('vapeandgo', 36279)['barcodes']]);
    $hits = [];
    foreach (Gtin::listingKeys(R('electrofag', 7409)['barcodes'])['usable'] as $k) {
        foreach ($idx['by_key'][$k] ?? [] as $id) {
            $hits[$id] = true;
        }
    }
    eq(count($hits), 2);
    eq(Band::provisional(['lane' => 'barcode', 'flags' => ['multi_sku_gtin']])['band'], Band::CONFLICT);
    $v = Veto::check(V(38563), V(36279));
    ok(in_array('pack', codes($v), true), '1-pack vs 2-pack');
});
t('trap: shared VPG barcode on Corex 2.0 and 3.0 is not usable', function () {
    $idx = Gtin::index([31810 => R('vapeandgo', 31810)['barcodes'], 41615 => R('vapeandgo', 41615)['barcodes']]);
    ok(isset($idx['multi']['6943498697557']));
});
t('trap: placeholder decoy (A#30 vs the VPG parent row) and landing listing A#461', function () {
    ok(in_array('placeholder', codes(pair(30, 40391)), true));
    truePair(30, 40378);
    ok(A(461)['is_placeholder']);
    eq(Band::provisional(['lane' => 'ignore', 'is_placeholder' => true])['band'], Band::IGNORE);
});
t('trap: strength missing among strength siblings is never Key', function () {
    $a = N(['variant_title' => 'Banana Kiwi Ice Riot Squad BAR EDTN 10ml Nic Salt E Liquid', 'brand' => 'Riot Squad']);
    $s = V(12938);
    $res = Veto::check($a, $s, 1, ['s_strength_sibling' => true]);
    ok(in_array('strength_missing', $res['flags'], true));
    $ev = ['lane' => 'barcode', 'target' => 12938, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    ok(Band::final($ev, ['outcome' => 'match', 'chosen_id' => 12938, 'confidence' => 100, 'units_per_item' => 1])['band'] !== Band::KEY);
});
t('trap: barcode and transfer disagree (A#3648) is a Conflict', function () {
    eq(Band::provisional(['lane' => 'barcode', 'target' => 36645, 'flags' => ['barcode_transfer_disagree']])['band'], Band::CONFLICT);
});

// ═════════════════════════════ 4 true pairs that must not be vetoed ═════════════════════════════
t('true pairs (barcode pairs, naming noise only) are not vetoed', function () {
    foreach ([[7531, 38228], [3308, 33157], [10952, 45513], [886, 38916], [9403, 29794], [4877, 44970], [3249, 29380],
        [6294, 34922], [9347, 37053], [9577, 11714], [2215, 30477], [1628, 8553], [4280, 847], [3648, 36645], [6067, 48]] as [$a, $v]) {
        truePair($a, $v);
    }
});
t('ALT puff attribute error (600 on a 6000 device) does not veto, but blocks Key', function () {
    $res = truePair(11850, 45768);
    ok(in_array('internal_conflict', $res['flags'], true));
    ok(bestBand(11850, 45768) !== Band::KEY);
});
t('"Refillable" printed next to a flavour is a data conflict, not a form veto', function () {
    $res = truePair(5396, 37097);
    ok(in_array('internal_conflict', $res['flags'], true));
});
t('a clean barcode pair can reach Key only with the judge', function () {
    eq(bestBand(7531, 38228), Band::KEY);
    $res = pair(7531, 38228);
    $ev = ['lane' => 'barcode', 'target' => 38228, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    eq(Band::provisional($ev)['band'], null, 'no band without the judge');
    eq(Band::provisional($ev)['ceiling'], Band::KEY);
});

// ═════════════════════════════ 5 pilot-1 misses (regression: each must be vetoed or flagged, never Key) ═════════════════════════════
/** A trap that must carry this soft flag (and so can never reach Key). */
function flagged(int $aid, int $vid, string $flag): array
{
    $res = pair($aid, $vid);
    ok(in_array($flag, $res['flags'], true), "A#$aid vs V#$vid: expected flag $flag, got flags " . json_encode($res['flags']) . ' vetoes ' . json_encode(codes($res)));
    ok(bestBand($aid, $vid) !== Band::KEY, "A#$aid vs V#$vid banded Key");
    return $res;
}
/** A true pair that stays clean enough to reach Key with an agreeing judge. */
function keyPair(int $aid, int $vid): void
{
    truePair($aid, $vid);
    eq(bestBand($aid, $vid), Band::KEY, "A#$aid vs V#$vid best band");
}

t('pilot-1 L6/L14/L22: Bar Juice 5000 vs Bar Salts / Vapes Bar Ghost (umbrella "bar", one-sided 5000)', function () {
    $r = flagged(613, 9700, 'line_number_one_side');                // Strawberry Ice: Bar Juice 5000 vs Bar Salts
    ok($r['fields']['brand_line'] !== 'agree', '"bar" alone must not make the lines agree');
    flagged(551, 28034, 'line_number_one_side');                     // Gummy Bear: vs Bar Salts
    trap(551, 28262, 'line_word');                                   // Gummy Bear: vs Vapes Bar Ghost Salts (juice vs ghost)
    trap(536, 28223, 'line_word');                                   // Fresh Mint: vs Vapes Bar Ghost Salts
    flagged(536, 29515, 'line_number_one_side');                     // Fresh Mint: vs Bar Salts
    keyPair(613, 26525);
    keyPair(551, 12773);
    keyPair(536, 10851);
});
t('pilot-1 L16: ELFLIQ Spearmint vs Pod Salt Core Spearmint (generic brand words; line_word)', function () {
    trap(2261, 36999, 'line_word');
    ok(pair(2261, 36999)['fields']['brand_line'] !== 'agree', '"pod"/"salt" must not make Elf Bar agree with Pod Salt');
    trap(2261, 36572, 'flavour_diff');                               // Spearmint vs Gami: Gami is a stated flavour now
    trap(2261, 30464, 'flavour_diff');                               // Spearmint vs Rinbo
    keyPair(2261, 10740);
});
t('pilot-1 L30: IVG Original Salts vs IVG Intense Vanilla Biscuit (line_word)', function () {
    trap(13130, 37702, 'line_word');
    keyPair(13130, 46992);
});
t('pilot-1 L9: Elfliq Strawberry Ice vs Strawberry Ice Cream (Snoow) (Electrofag split + VPG segment split)', function () {
    eq(A(2265)['flavour_tokens'], ['strawberry', 'ice']);
    eq(V(11708)['flavour_tokens'], ['strawberry', 'ice', 'cream']);
    trap(2265, 11708, 'flavour_superset');
    keyPair(2265, 11706);
});
t('pilot-1 pairs L53: Lost Mary BM600 vs Tappo (model letters are line words; one-sided model number)', function () {
    trap(5326, 30514, 'line_word');
    ok(in_array('line_number_one_side', pair(5326, 30514)['flags'], true), 'BM600 vs Tappo: 600 on one side only');
    truePair(5326, 36318);
});
t('pilot-1 pairs L20: single nicotine shot vs "10 x 10ml" / "20 x 10ml" multipacks (multipack direction)', function () {
    trap(6067, 51, 'multipack');
    trap(6067, 27583, 'multipack');
    truePair(6067, 48);
    // the other direction: a listing multiple against a single item is vetoed unless units_per_item is proposed
    $multi = N(['variant_title' => '10 x 10ml Nic Nic Nicotine Shots - 18mg/ml - 100% VG', 'brand' => 'Nic Nic']);
    $single = N(['variant_title' => 'Nic Nic Nicotine Shots - 18mg/ml - 100% VG', 'brand' => 'Nic Nic']);
    ok(in_array('multipack', codes(Veto::check($multi, $single, 1)), true), 'listing 10 x vs single item, u=1');
    ok(!in_array('multipack', codes(Veto::check($multi, $single, 10)), true), 'u=10 proposed: the pack arithmetic decides');
    ok(in_array('multipack', codes(Veto::check($single, $multi, 10)), true), 'an item multiple against a single listing: never');
});
t('pilot-1 pairs L16: "Raspberrry" typo is a flavour word (fuzzy, one edit, 6+ letters)', function () {
    ok(Flavour::isWord('raspberrry'));
    ok(Flavour::isWord('strawbery'));
    ok(!Flavour::isWord('elfliq'), 'a line word is not a flavour word');
    ok(!Flavour::isWord('mint') || Flavour::isConstWord('mint'));
    trap(5320, 36306, 'flavour_superset');                           // Blueberry Sour Raspberrry vs Blueberry
    keyPair(5320, 36307);
});
t('pilot-1: seed-vocabulary flavour names (Oasis, Tiger Blood, Mad Blue, Mr Blue) are stated flavours', function () {
    foreach (['oasi', 'gami', 'rinbo', 'tiger', 'mad', 'mr'] as $w) {
        ok(Flavour::isWord($w), "$w is a seed-vocabulary flavour word");
    }
    foreach (['crystal', 'original', 'bar', 'hayati', 'elfliq', 'intense'] as $w) {
        ok(!Flavour::isWord($w), "$w is a line word, not a flavour");
    }
    trap(6072, 42424, 'flavour_diff');                               // loo L2: Oasis vs Menthol
    trap(6072, 42419, 'flavour_diff');                               // Oasis vs Cherry Sour Raspberry
    trap(6073, 12721, 'flavour_diff');                               // pairs L28: Oasis vs Menthol
    trap(6073, 28673, 'flavour_diff');                               // Oasis vs Rainbow
    trap(5879, 42426, 'flavour_diff');                               // pairs L34: Menthol vs Oasis
    trap(8334, 12724, 'flavour_diff');                               // pairs L35: Tiger Blood vs Mr Blue
    trap(8334, 26646, 'flavour_diff');                               // Tiger Blood vs Cola
    trap(3296, 29364, 'flavour_diff');                               // pairs L32: Mad Blue vs Mr Blue
    trap(3296, 28194, 'flavour_diff');                               // Mad Blue vs Blue Fusion
    foreach ([[6072, 42426], [6073, 35274], [5879, 42424], [8334, 12730], [3296, 28173]] as [$a, $v]) {
        keyPair($a, $v);
    }
});
t('pilot-1 pairs L49: VPG "<Line> Nic Salts - <Flavour> - 10ml" split (was flavour "crystal")', function () {
    eq(V(28215)['flavour_tokens'], ['fresh', 'menthol', 'mojito']);
    trap(3302, 28215, 'flavour_superset');                           // Menthol vs Fresh Menthol Mojito
    keyPair(3302, 33145);
    $f = N(['variant_title' => 'Elfliq Nic Salt by Elf Bar - Strawberry Ice Cream(Snoow) - 10ml - 20mg', 'brand' => 'Elf Bar']);
    eq([$f['flavour_tokens'], $f['flavour_src']], [['strawberry', 'ice', 'cream'], 'title_segment']);
    $f = N(['variant_title' => 'Oasis Nic Salt E-Liquid by Elux Legend 10ml | 5mg']);
    eq([$f['flavour_tokens'], $f['flavour_src']], [['oasis'], 'title_by_pattern'], 'no later segment: the by-pattern stands');
});
t('Electrofag title patterns: line first and flavour first', function () {
    eq([A(613)['flavour_tokens'], A(613)['flavour_src']], [['strawberry', 'ice'], 'title_pattern']);   // Bar Juice 5000 Strawberry Ice
    eq(A(2261)['flavour_tokens'], ['spearmint']);                                                      // ELFLIQ Spearmint
    eq(A(6072)['flavour_tokens'], ['oasis']);                                                          // Oasis Elux Legend
    eq(A(8334)['flavour_tokens'], ['tiger', 'blood']);
    eq(A(3296)['flavour_tokens'], ['mad', 'blue']);                                                    // Hayati Pro Max Mad Blue
    $sp = TitlePattern::split(TitlePattern::headTokens('ske crystal original cherry ice 10ml nic salt e liquid'), ['crystal', 'bar'], ['ske', 'crystal', 'original']);
    eq([$sp['flavour'], $sp['pattern']], [['cherry', 'ice'], 'line_first']);
    $sp = TitlePattern::split(TitlePattern::headTokens('melon xl riot squad bar edtn 10ml nic salt e liquid'), ['riot', 'squad'], []);
    eq([$sp['flavour'], $sp['line'], $sp['pattern']], [['melon', 'xl'], ['riot', 'squad', 'bar', 'edtn'], 'flavour_first']);
    eq(TitlePattern::split(TitlePattern::headTokens('hayati pro max plus 6k prefilled pods'), ['hayati'], []), null, 'a product shell has no flavour');
    $lex = TitlePattern::lexicon([
        ['brand' => 'Elf Bar', 'product_id' => 1, 'product_title' => 'ELFLIQ Spearmint 10ml Nic Salt E Liquid'],
        ['brand' => 'Elf Bar', 'product_id' => 2, 'product_title' => 'ELFLIQ Gami 10ml Nic Salt E Liquid'],
        ['brand' => 'Elf Bar', 'product_id' => 3, 'product_title' => 'ELFLIQ Rinbo 10ml Nic Salt E Liquid'],
        ['brand' => 'Elf Bar', 'product_id' => 4, 'product_title' => 'ELFLIQ Gami Ice 10ml Nic Salt E Liquid'],
        ['brand' => 'Elf Bar', 'product_id' => 5, 'product_title' => 'ELFLIQ Gami Sour 10ml Nic Salt E Liquid'],
    ]);
    eq($lex['elf bar'], ['elfliq'], 'shared non-flavour words only ("gami" is a flavour even on 3 products)');
});
t('residual keeps the other side\'s line words that are flavour words', function () {
    $base = ['brand_raw' => 'Brandq', 'brand_family' => ['brandq'], 'paren_tokens' => [], 'line_models' => []];
    $l = $base + ['flavour_tokens' => null, 'id_tokens' => ['lemon'], 'line_tokens' => [], 'full_tokens' => ['brandq', 'lemon', 'nic', 'salt']];
    $s = $base + ['flavour_tokens' => ['cherry'], 'id_tokens' => ['cherry', 'lemon'], 'line_tokens' => ['lemon'],
        'full_tokens' => ['cherry', 'nic', 'salt', 'by', 'brandq', 'lemon']];
    $fc = Veto::flavourCompare($l, $s);
    eq($fc['veto'], 'flavour_superset', 'v1.0 dropped "lemon" (an item line word) and compared nothing');
});
t('line_word: a mismatch explained by a pending alias is flagged, not vetoed, and routed to Can\'t tell', function () {
    $l = N(['product_title' => 'The Crystal Pro Max Banana Ice 10ml Nic Salt E Liquid', 'variant_title' => 'The Crystal Pro Max Banana Ice 10ml Nic Salt E Liquid - 20mg', 'brand' => 'Crystal Pro Max']);
    $s = N(['variant_title' => 'Banana Ice Nic Salt E-liquid by Hayati Pro Max 10ml - 20mg', 'brand' => 'Hayati']);
    $res = Veto::check($l, $s);
    ok(!in_array('line_word', codes($res), true), 'no line_word veto');
    ok(in_array('line_alias_pending', $res['flags'], true), 'line_alias_pending flag');
    $ev = ['lane' => 'barcode', 'target' => 1, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    eq(Band::provisional($ev)['ceiling'], Band::CANT_TELL);
    eq(Band::final($ev, ['outcome' => 'match', 'chosen_id' => 1, 'confidence' => 99, 'units_per_item' => 1])['band'], Band::CANT_TELL);
    eq(Veto::aliasPending(['original'], ['bar']), 'SKE Crystal Original = SKE Crystal Bar');
    eq(Veto::aliasPending(['original'], ['intense']), null);
});
t('Key needs the judge to pick the target at confidence >= 85 (b2.1, M26; b2.0: 90, pilot-1 recommendation 9)', function () {
    $key = ['lane' => 'barcode', 'target' => 7, 'target_vetoes' => [], 'target_flags' => [], 'candidates' => [['id' => 7, 'prescore' => 90, 'vetoes' => []]]];
    eq(Band::KEY_MIN_CONFIDENCE, 85);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 84, 'units_per_item' => 1])['band'], Band::CHECK);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 85, 'units_per_item' => 1])['band'], Band::KEY);
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 89, 'units_per_item' => 1])['band'], Band::KEY);
    eq(Band::final(['lane' => 'transfer'] + $key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 85, 'units_per_item' => 1])['band'], Band::KEY);
    // b2.0 replayed (Reband's check of a stored band): 89 was Check
    eq(Band::final($key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 89, 'units_per_item' => 1], Band::KEY_MIN_BY_VERSION['b2.0'])['band'], Band::CHECK);
    // 85-89 without a key (candidates lane) stays Check; a vetoed or soft-flagged target is never Key
    eq(Band::final(['lane' => 'candidates', 'candidates' => [['id' => 7, 'prescore' => 90, 'vetoes' => []]]], ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 88, 'units_per_item' => 1])['band'], Band::CHECK);
    eq(Band::final(['target_vetoes' => [['code' => 'strength']]] + $key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 99, 'units_per_item' => 1])['band'], Band::CONFLICT);
    eq(Band::final(['target_flags' => ['price_outlier']] + $key, ['outcome' => 'match', 'chosen_id' => 7, 'confidence' => 88, 'units_per_item' => 1])['band'], Band::CHECK);
});
t('judge card: candidate strength set is allow-listed and blind', function () {
    $c = JudgeCard::card('C1', R('vapeandgo', 10740), V(10740), [20, 10.0, 5]);
    eq($c['product_strengths_mg'], [5, 10, 20]);
    JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'candidates' => [$c]]]], array_map('strval', R('vapeandgo', 10740)['barcodes']));
});

// ═════════════════════════════ 6 run3 follow-ups (M29) ═════════════════════════════
t('run3 (a): Riot Squad "<Flavour> XL ... BAR EDTN" keeps XL in the flavour with the real line lexicon (false line_modifier veto)', function () {
    global $fx;
    // the condition behind the bug: "xl" is a line-lexicon word of Riot Squad on Electrofag (3+ products)
    ok(in_array('xl', $fx['ctx']['electrofag']['5820']['line_lexicon'], true), 'the fixture carries the real lexicon');
    foreach ([5820 => ['mango', 'xl'], 1077 => ['cherry', 'xl'], 6484 => ['peach', 'xl'], 280 => ['apple', 'xl']] as $aid => $flav) {
        eq(A($aid)['flavour_tokens'], $flav, "A#$aid flavour");
        eq(A($aid)['line_modifiers'], [], "A#$aid has no line modifier");
        eq(A($aid)['line_tokens'], ['riot', 'squad', 'bar', 'edtn'], "A#$aid line");
    }
    // run3: these four true pairs were "ai_match_on_vetoed_pair" Conflicts (line_modifier "listing +xl")
    foreach ([[5820, 34603], [1077, 34596], [6484, 30781], [280, 34599]] as [$a, $v]) {
        keyPair($a, $v);
        eq(pair($a, $v)['fields']['brand_line'], 'agree', "A#$a vs V#$v brand/line");
    }
    trap(280, 34601, 'strength');                                    // Apple XL 5mg vs Apple XL 20mg
    keyPair(7966, 34556);                                            // Sour Cherry Apple (no XL) stays clean
    // the split itself, with the lexicon holding the modifier
    $lex = ['bar', 'edtn', 'riot', 'squad', 'xl'];
    $sp = TitlePattern::split(TitlePattern::headTokens('melon xl riot squad bar edtn 10ml nic salt e liquid'), ['riot', 'squad'], $lex);
    eq([$sp['flavour'], $sp['line'], $sp['pattern']], [['melon', 'xl'], ['riot', 'squad', 'bar', 'edtn'], 'flavour_first']);
    // line first: modifiers stay in the line ("Hayati Pro Max Cherry Ice")
    $sp = TitlePattern::split(TitlePattern::headTokens('hayati pro max cherry ice 10ml nic salt e liquid'), ['hayati'], ['max', 'pro']);
    eq([$sp['flavour'], $sp['line'], $sp['pattern']], [['cherry', 'ice'], ['hayati', 'pro', 'max'], 'line_first']);
    // a flavour-first line of a modifier and glue only keeps the modifier (no brand/lexicon word left to be the line)
    $sp = TitlePattern::split(['mango', 'xl', 'bar'], ['zzz'], ['xl']);
    eq([$sp['flavour'], $sp['line']], [['mango'], ['xl', 'bar']]);
    eq(TitlePattern::VERSION, 'tp1.1');
    // XL on one side only is never Key (a flavour word on one side: flavour_extra)
    $plain = N(['variant_title' => 'Mango Nic Salt E-Liquid by Riot Squad Bar Edition 10ml | 5mg', 'brand' => 'Riot Squad Nic Salts']);
    $res = Veto::check(A(5820), $plain);
    ok($res['vetoes'] !== [] || $res['flags'] !== [], 'Mango XL vs Mango is vetoed or flagged: ' . json_encode($res));
    $ev = ['lane' => 'barcode', 'target' => 1, 'target_vetoes' => $res['vetoes'], 'target_flags' => $res['flags'], 'candidates' => []];
    ok(Band::final($ev, ['outcome' => 'match', 'chosen_id' => 1, 'confidence' => 100, 'units_per_item' => 1])['band'] !== Band::KEY, 'never Key');
});
t('run3 (b): "B Gum" / "BGum" is Bubblegum', function () {
    eq(Flavour::canon(['blueberry', 'b', 'gum']), ['blueberry', 'bubblegum']);
    eq(Flavour::canon(['strawberry', 'watermelon', 'bgum']), ['strawberry', 'watermelon', 'bubblegum']);
    ok(Flavour::same(['blueberry', 'b', 'gum'], ['blueberry', 'bubblegum']));
    ok(Flavour::same(['watermelon', 'b', 'gum'], ['watermelon', 'bubble', 'gum']), '"Bubble Gum" written apart');
    eq(Flavour::VERSION, 'f2.1');
    // run3: Hayati Pro Max Plus "Blueberry Bubblegum" vs "Blueberry B Gum" were flavour_diff Conflicts
    keyPair(3398, 46162);
    keyPair(3352, 45730);
    truePair(12256, 46162);                                           // "Blueberry B Gum" on both sides stays clean
    truePair(878, 36968);                                             // Bloody Bar "Strawberry Watermelon Bubblegum" vs "... Bgum"
    truePair(9867, 43180);                                            // VYLO Duo "Straw Bubblegum / Green Apple Bubblegum" vs "B Gum"
    // a stated B Gum is a flavour: "Strawberry Watermelon" vs "Watermelon B Gum / Strawberry B Gum" is now a hard veto
    trap(3652, 36925, 'flavour_superset');
    $a = N(['variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - Blueberry B Gum', 'brand' => 'Hayati']);
    $b = N(['variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - Blueberry', 'brand' => 'Hayati']);
    $c = N(['variant_title' => 'Hayati Pro Max Plus 6000 Prefilled Pod Kit - Blueberry Bubblegum Ice', 'brand' => 'Hayati']);
    ok(in_array('flavour_superset', codes(Veto::check($a, $b)), true), 'B Gum vs none');
    ok(in_array('flavour_superset', codes(Veto::check($a, $c)), true), 'B Gum vs Bubblegum Ice');
});
t('run3 (c): one empty scratch directory per judge chunk, apart from the run and private folders', function () {
    $base = sys_get_temp_dir() . '/cw_judge_scratch_' . getmypid() . '_' . bin2hex(random_bytes(4));
    $run = "$base/fm/run9";
    $private = "$base/fm/private/run9";
    mkdir($run . '/judge', 0700, true);
    mkdir($private, 0700, true);
    $rm = function (string $d) use (&$rm): void {
        foreach (array_diff(scandir($d) ?: [], ['.', '..']) as $f) {
            is_dir("$d/$f") && !is_link("$d/$f") ? $rm("$d/$f") : unlink("$d/$f");
        }
        rmdir($d);
    };
    try {
        $root = JudgeScratch::defaultRoot($run);
        eq($root, "$base/fm/judge_scratch/run9");
        $dirs = JudgeScratch::prepare($root, ['run9_c001', 'run9_c002', 'run9_c003'], [$run, $private]);
        eq(array_keys($dirs), ['run9_c001', 'run9_c002', 'run9_c003']);
        eq(count(array_unique($dirs)), 3, 'every judge has its own directory');
        foreach ($dirs as $c => $d) {
            ok(is_dir($d) && str_ends_with($d, "/$c"), "$c directory");
            eq(fileperms($d) & 0777, 0700, "$c mode");
            eq(array_values(array_diff(scandir($d) ?: [], ['.', '..'])), [], "$c empty");
        }
        eq(JudgeScratch::prepare($root, ['run9_c001'], [$run, $private]), ['run9_c001' => $dirs['run9_c001']], 'an empty directory is reused');
        file_put_contents($dirs['run9_c002'] . '/view.txt', 'a judge note');
        $refused = function (callable $f, string $why) {
            try {
                $f();
            } catch (RuntimeException) {
                return;
            }
            throw new RuntimeException("not refused: $why");
        };
        $refused(fn () => JudgeScratch::prepare($root, ['run9_c002'], [$run, $private]), 'a directory holding a previous attempt\'s files');
        $refused(fn () => JudgeScratch::prepare("$run/scratch", ['run9_c004'], [$run, $private]), 'a root inside the run folder');
        $refused(fn () => JudgeScratch::prepare("$private/x", ['run9_c004'], [$run, $private]), 'a root inside the private folder');
        $refused(fn () => JudgeScratch::prepare("$base/fm", ['run9_c004'], [$run, $private]), 'a root that holds the run folder');
        $refused(fn () => JudgeScratch::prepare($root, ['run9_c004', 'run9_c004'], [$run, $private]), 'one chunk named twice');
        $refused(fn () => JudgeScratch::prepare($root, ['../run9_c004'], [$run, $private]), 'a chunk name that is a path');
        $refused(fn () => JudgeScratch::prepare('relative/root', ['run9_c004'], [$run, $private]), 'a relative root');
        ok(!is_dir("$root/run9_c004"), 'a refused call creates nothing');
        ok(str_contains(JudgeScratch::INSTRUCTION, 'scratch_dir'), 'the chunk file tells the judge where');
    } finally {
        $rm($base);
    }
});
t('run3 (d): one form enum for Normalizer, Veto and JudgeCard; free-text forms map onto it', function () {
    global $fx;
    eq(Normalizer::FORMS, Form::ALL);
    eq(Normalizer::FORM_CLASS, Form::CLASS_OF);
    $forms = Form::ALL;
    $classed = array_keys(Form::CLASS_OF);
    sort($forms);
    sort($classed);
    eq($classed, $forms, 'every form has a class, and only forms do');
    foreach (['electrofag' => 'A', 'vapeandgo' => 'V'] as $site => $fn) {
        foreach (array_keys($fx['rows'][$site]) as $id) {
            $f = $fn((int) $id);
            ok($f['form'] === null || Form::isForm($f['form']), "$site#$id form " . json_encode($f['form']));
            ok($f['form_sub'] === null || in_array($f['form_sub'], Form::SUBS, true), "$site#$id form_sub " . json_encode($f['form_sub']));
            $card = JudgeCard::card('L1', R($site, (int) $id), $f);
            ok(!isset($card['extracted']['form']) || Form::isForm($card['extracted']['form']['value']), "$site#$id card form " . json_encode($card['extracted']['form'] ?? null));
            ok(!isset($card['extracted']['form_sub']) || in_array($card['extracted']['form_sub']['value'], Form::SUBS, true), "$site#$id card form_sub");
            eq(Veto::consumable($f), Form::flavoured($f['form'], $f['form_sub']), "$site#$id consumable");
        }
    }
    // the card shows the enum value and the sub apart (run3's cards said "pod_kit (prefilled)")
    $f = N(['variant_title' => 'Lost Mary BM6000 Prefilled Pod Kit - Cherry Ice | 20mg', 'brand' => 'Lost Mary']);
    $c = JudgeCard::card('L1', row(['variant_title' => 'Lost Mary BM6000 Prefilled Pod Kit - Cherry Ice | 20mg']), $f);
    eq([$c['extracted']['form']['value'], $c['extracted']['form_sub']['value']], ['pod_kit', 'prefilled']);
    JudgeCard::assertBlind(['items' => [['ref' => 'L1', 'listing' => $c]]], []);
    // flavoured forms (Veto::consumable, the flavour split and the seed vocabulary share Form::flavoured)
    foreach ([['nic_salt', null, true], ['prefilled_pod', null, true], ['pod_kit', 'prefilled', true], ['pod_kit', 'refillable', false],
        ['pod_kit', null, false], ['kit', 'prefilled', false], ['coil', null, false], [null, null, false]] as [$form, $sub, $want]) {
        eq(Form::flavoured($form, $sub), $want, Form::label($form, $sub));
        eq(Veto::consumable(['form' => $form, 'form_sub' => $sub]), $want, 'consumable ' . Form::label($form, $sub));
    }
    // the 11 spellings run3's judges wrote for listing_extract.form, the old card label, label(), the enum itself
    foreach ([
        'prefilled pod kit' => ['pod_kit', 'prefilled'], 'prefilled_pod_kit' => ['pod_kit', 'prefilled'], 'pod kit' => ['pod_kit', null],
        'refillable pod kit' => ['pod_kit', 'refillable'], 'nic salt e-liquid' => ['nic_salt', null], 'refillable_pod' => ['refill_pod_cartridge', 'refillable'],
        'vape_kit' => ['kit', null], 'prefilled pods' => ['prefilled_pod', null], 'vape pod kit' => ['pod_kit', null],
        'replacement pods' => ['refill_pod_cartridge', null], 'e-liquid' => ['e_liquid', null],
        'pod_kit (prefilled)' => ['pod_kit', 'prefilled'], 'pod_kit/prefilled' => ['pod_kit', 'prefilled'], 'Nic Salt' => ['nic_salt', null],
        'disposable' => ['disposable', null], 'Disposables' => ['disposable', null], 'Coils' => ['coil', null], 'E Liquids' => ['e_liquid', null],
        'Nicotine Pouches' => ['other', 'nicotine_pouch'], 'Shortfill' => ['shortfill', null], 'Batteries' => ['battery', null],
        'accessories' => ['accessory', null], 'Nic Shots' => ['nic_shot', null], 'Long Fill' => ['shortfill', 'longfill'],
    ] as $raw => [$form, $sub]) {
        eq(Form::canonical($raw), ['form' => $form, 'form_sub' => $sub], $raw);
    }
    foreach (['banana', '', 'pod_kit (banana)x', 'kit kat'] as $raw) {
        eq(Form::canonical($raw), null, json_encode($raw));
    }
    eq(Form::canonical('pod_kit (banana)'), ['form' => 'pod_kit', 'form_sub' => null], 'an unknown sub is dropped');
    // Veto names both forms the same way
    $kit = N(['variant_title' => 'Lost Mary BM6000 Prefilled Pod Kit - Cherry Ice']);
    $pods = N(['variant_title' => 'Cherry Ice Lost Mary BM6000 Refill Pack']);
    $v = array_values(array_filter(Veto::check($kit, $pods)['vetoes'], fn ($x) => $x['code'] === 'form'));
    eq($v[0]['detail'] ?? null, Form::label($kit['form'], $kit['form_sub']) . ' vs ' . Form::label($pods['form'], $pods['form_sub']));
    eq([Normalizer::VERSION, Veto::VERSION], ['n2.1', 'v2.1']);
});
t('run3 (e): Band labels a key-lane no-match below 80 itself; unrecognised_outcome is only an unknown outcome', function () {
    $key = ['lane' => 'barcode', 'target' => 7, 'target_vetoes' => [], 'target_flags' => [], 'candidates' => [['id' => 7, 'prescore' => 90, 'vetoes' => []]]];
    $nm = fn (int $conf, string $out = 'no_match_in_list') => ['outcome' => $out, 'chosen_id' => null, 'confidence' => $conf, 'units_per_item' => null];
    foreach ([79, 75, 70, 65, 0] as $conf) {
        eq(Band::final($key, $nm($conf)), ['band' => Band::CANT_TELL, 'reasons' => ['ai_no_match_on_key_below_80_' . $conf]], "barcode $conf");
        eq(Band::final(['lane' => 'transfer'] + $key, $nm($conf))['reasons'], ['ai_no_match_on_key_below_80_' . $conf], "transfer $conf");
        eq(Band::final(['pending_alias' => true] + $key, $nm($conf))['band'], Band::CANT_TELL, "alias $conf");
    }
    eq(Band::final($key, $nm(80)), ['band' => Band::CONFLICT, 'reasons' => ['ai_no_match_on_key']]);
    eq(Band::final(['lane' => 'candidates', 'candidates' => [['id' => 1, 'prescore' => 80, 'vetoes' => []]]], $nm(75))['reasons'], ['no_match_fails_new_item']);
    eq(Band::final($key, $nm(90, 'maybe')), ['band' => Band::CANT_TELL, 'reasons' => ['unrecognised_outcome']]);
    eq(Band::final($key, $nm(40, 'maybe')), ['band' => Band::CANT_TELL, 'reasons' => ['unrecognised_outcome']]);
    eq(Band::final($key, $nm(75, 'cannot_tell'))['reasons'], ['cannot_tell_75']);
    // StoredBand (Reband, the bulk confirm) replays the same label a run3 proposal stored (assemble.php used to relabel it)
    $stored = ['lane' => 'barcode', 'lane_target' => ['cw_id' => 'CWP-1'], 'lane_flags' => [], 'target_vetoes' => [], 'target_soft_flags' => [],
        'key_possible' => true, 'key_blocked_by' => [], 'relabel_pending' => null, 'relabel_partners' => [],
        'ai' => ['outcome' => 'no_match_in_list', 'confidence' => 72, 'units_per_item' => null, 'chosen' => null, 'closest' => ['cw_id' => 'CWP-1'],
            'vetoes_on_chosen' => [], 'soft_flags_on_chosen' => [], 'warnings' => []],
        'candidates' => [['cw_id' => 'CWP-1', 'prescore' => 90, 'vetoes' => []]]];
    eq(StoredBand::evaluate($stored, Band::KEY_MIN_BY_VERSION['b2.0']), ['band' => Band::CANT_TELL, 'reasons' => ['ai_no_match_on_key_below_80_72'], 'error' => null]);
});

// ─────────────────────────────
foreach ($failures as $f) {
    fwrite(STDERR, $f . "\n");
}
echo json_encode(['passed' => $pass, 'failed' => $fail]) . "\n";
exit($fail === 0 ? 0 : 1);
