-- 0009_suppliers.sql — Inventory Phase I-2, task 1 (IM4): settings, VAT codes, suppliers, supplier items, price history and
-- the ERPNext seed-import runs (docs/decisions.md I38-I47).
--
--  * app_setting: typed settings (CW\Settings). READ-ONLY for cw_app; bin/settings.php --admin changes them (audit
--    setting.change). The company.* rows are empty placeholders until the owner provides the details (decision 9,
--    provisional): every PO PDF carries a "not confirmed - do not send" banner while company.confirmed is false.
--  * vat_code: the VAT codes a PO line carries (read-only, changed by migration).
--  * supplier: no bank, IBAN, sort-code or account column (decision 25, provisional: a test asserts it). A new or
--    re-activated supplier is active only after a second person approves it (review_task subject 'supplier', kind
--    approval, decision 11, provisional); identity changes of an active supplier open a non-blocking review.
--  * supplier_item: what a supplier sells us, pack -> central units; one preferred supplier item per item (the generated
--    preferred_sku_id + UNIQUE); last price mirrors the newest non-PO price history row (S4).
--  * supplier_item_price: price history, append-only for cw_app.
--  * import_run: one row per ERPNext seed file (backup copy only, decision 4); a file is imported once (sha256).
-- No backfill: every table starts empty except the seeded settings and VAT codes.

CREATE TABLE app_setting (
  setting_key   VARCHAR(64)  NOT NULL,
  value_type    ENUM('string','text','int','decimal','bool','date') NOT NULL,
  value_json    JSON         NOT NULL COMMENT 'JSON string/number/boolean; "" = not set',
  provisional   TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '1 = a default the owner has not confirmed',
  decision      VARCHAR(16)  NULL COMMENT 'owner decision (inventory plan §10) it implements',
  description   VARCHAR(500) NOT NULL,
  updated_actor VARCHAR(64)  NOT NULL DEFAULT 'system:migrate',
  updated_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (setting_key),
  CONSTRAINT ck_app_setting_key CHECK (REGEXP_LIKE(setting_key, '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$', 'c')),
  CONSTRAINT ck_app_setting_flags CHECK (provisional IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='settings: read-only for cw_app; bin/settings.php --admin changes them (audit setting.change)';
INSERT INTO app_setting (setting_key, value_type, value_json, provisional, decision, description) VALUES
 ('company.legal_name','string','""',1,'9','Legal name of the company that buys and owns the warehouse stock (PO letterhead)'),
 ('company.trading_name','string','""',1,'9','Trading name shown under the legal name'),
 ('company.address','text','""',1,'9','Registered / postal address, one line per line'),
 ('company.company_number','string','""',1,'9','Companies House number'),
 ('company.vat_number','string','""',1,'9','VAT registration number printed on POs'),
 ('company.phone','string','""',1,'9','Purchasing phone'),
 ('company.email','string','""',1,'9','Purchasing e-mail printed on POs'),
 ('company.delivery_address','text','""',1,'9','Warehouse delivery address printed on POs'),
 ('company.confirmed','bool','false',1,'9','false until the owner confirms the company details: every PO PDF carries a "not confirmed - do not send" banner'),
 ('costs.site_writeback','bool','false',1,'12','Write the CW average cost into the sites'' cost field: NOT built in Phase I-2'),
 ('suppliers.approval_due_days','int','3',1,'11','Days a supplier activation / import-route approval is due after it is requested'),
 ('suppliers.change_review','bool','true',1,'11','Identity changes of an active supplier open a (non-blocking) review task');

CREATE TABLE vat_code (
  code          VARCHAR(4)   NOT NULL,
  label         VARCHAR(64)  NOT NULL,
  rate_percent  DECIMAL(5,2) NOT NULL,
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  sort_order    SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  PRIMARY KEY (code),
  CONSTRAINT ck_vat_code_code CHECK (REGEXP_LIKE(code, '^[A-Z]{1,4}$', 'c')),
  CONSTRAINT ck_vat_code_rate CHECK (rate_percent >= 0 AND rate_percent <= 100),
  CONSTRAINT ck_vat_code_flags CHECK (is_active IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='VAT codes on PO lines (read-only, changed by migration)';
INSERT INTO vat_code (code, label, rate_percent, sort_order) VALUES
 ('S','Standard rate 20%',20.00,10),('R','Reduced rate 5%',5.00,20),('Z','Zero rate',0.00,30),
 ('E','Exempt',0.00,40),('RC','Reverse charge',0.00,50),('OS','Outside the scope of UK VAT',0.00,60);

CREATE TABLE supplier (
  id                        INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                      VARCHAR(16)   NOT NULL,
  name                      VARCHAR(128)  NOT NULL,
  legal_name                VARCHAR(160)  NULL,
  status                    ENUM('draft','pending_approval','active','inactive') NOT NULL DEFAULT 'draft',
  version                   INT UNSIGNED  NOT NULL DEFAULT 1,
  company_number            VARCHAR(16)   NULL,
  vat_number                VARCHAR(20)   NULL,
  address_line1             VARCHAR(128)  NULL,
  address_line2             VARCHAR(128)  NULL,
  city                      VARCHAR(64)   NULL,
  postcode                  VARCHAR(16)   NULL,
  country                   CHAR(2)       NOT NULL DEFAULT 'GB',
  contact_name              VARCHAR(128)  NULL,
  email                     VARCHAR(191)  NULL COMMENT 'where POs are sent',
  phone                     VARCHAR(32)   NULL,
  contacts_note             VARCHAR(500)  NULL,
  payment_terms             VARCHAR(100)  NULL,
  payment_terms_days        SMALLINT UNSIGNED NULL,
  default_lead_days         TINYINT UNSIGNED NULL,
  review_days               TINYINT UNSIGNED NULL COMMENT 'order cycle (reorder R); NULL = reorder.default_review_days',
  min_order_value           DECIMAL(12,2) NULL,
  default_vat_code          VARCHAR(4)    NOT NULL DEFAULT 'S',
  currency                  CHAR(3)       NOT NULL DEFAULT 'GBP',
  is_overseas               TINYINT(1)    NOT NULL DEFAULT 0,
  import_route              VARCHAR(1000) NULL COMMENT 'overseas: how/where UK duty stamps are applied before arrival',
  import_route_file_id      BIGINT UNSIGNED NULL,
  import_route_approved_by  INT UNSIGNED  NULL,
  import_route_approved_at  DATETIME(6)   NULL,
  dd_checked_on             DATE          NULL,
  dd_checked_by             INT UNSIGNED  NULL,
  dd_evidence               VARCHAR(1000) NULL,
  dd_evidence_file_id       BIGINT UNSIGNED NULL,
  dd_next_review_on         DATE          NULL,
  erp_name                  VARCHAR(140)  NULL COMMENT 'ERPNext Supplier.name (seed import key)',
  notes                     VARCHAR(1000) NULL,
  created_by                INT UNSIGNED  NULL,
  created_actor             VARCHAR(64)   NOT NULL,
  created_at                DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_by                INT UNSIGNED  NULL,
  updated_actor             VARCHAR(64)   NOT NULL,
  updated_at                DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  details_changed_by        INT UNSIGNED  NULL COMMENT 'last person who changed an approval-relevant field',
  details_changed_at        DATETIME(6)   NULL,
  approved_by               INT UNSIGNED  NULL,
  approved_at               DATETIME(6)   NULL,
  deactivated_by            INT UNSIGNED  NULL,
  deactivated_at            DATETIME(6)   NULL,
  deactivate_reason         VARCHAR(500)  NULL,
  last_decision_note        VARCHAR(500)  NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_code (code),
  UNIQUE KEY uq_supplier_erp_name (erp_name),
  KEY ix_supplier_status (status, name),
  KEY ix_supplier_name (name),
  KEY ix_supplier_dd (dd_next_review_on),
  KEY ix_supplier_vat (default_vat_code),
  KEY ix_supplier_route_file (import_route_file_id), KEY ix_supplier_dd_file (dd_evidence_file_id),
  KEY ix_supplier_created_by (created_by), KEY ix_supplier_updated_by (updated_by), KEY ix_supplier_changed_by (details_changed_by),
  KEY ix_supplier_approved_by (approved_by), KEY ix_supplier_route_by (import_route_approved_by), KEY ix_supplier_dd_by (dd_checked_by),
  KEY ix_supplier_deactivated_by (deactivated_by),
  CONSTRAINT fk_supplier_vat FOREIGN KEY (default_vat_code) REFERENCES vat_code (code),
  CONSTRAINT fk_supplier_route_file FOREIGN KEY (import_route_file_id) REFERENCES stored_file (id),
  CONSTRAINT fk_supplier_dd_file FOREIGN KEY (dd_evidence_file_id) REFERENCES stored_file (id),
  CONSTRAINT fk_supplier_created_by FOREIGN KEY (created_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_updated_by FOREIGN KEY (updated_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_changed_by FOREIGN KEY (details_changed_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_approved_by FOREIGN KEY (approved_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_route_by FOREIGN KEY (import_route_approved_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_dd_by FOREIGN KEY (dd_checked_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_deactivated_by FOREIGN KEY (deactivated_by) REFERENCES staff_user (id),
  CONSTRAINT ck_supplier_code CHECK (REGEXP_LIKE(code, '^[A-Z0-9][A-Z0-9_-]{1,15}$', 'c')),
  CONSTRAINT ck_supplier_country CHECK (REGEXP_LIKE(country, '^[A-Z]{2}$', 'c')),
  CONSTRAINT ck_supplier_currency CHECK (currency = 'GBP'),
  CONSTRAINT ck_supplier_flags CHECK (is_overseas IN (0,1)),
  CONSTRAINT ck_supplier_active CHECK (status <> 'active' OR approved_at IS NOT NULL),
  CONSTRAINT ck_supplier_inactive CHECK ((status = 'inactive') = (deactivated_at IS NOT NULL)),
  CONSTRAINT ck_supplier_route CHECK (import_route_approved_at IS NULL OR (is_overseas = 1 AND import_route IS NOT NULL)),
  CONSTRAINT ck_supplier_dd CHECK (dd_next_review_on IS NULL OR dd_checked_on IS NULL OR dd_next_review_on >= dd_checked_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='suppliers (IM4). No bank details (decision 25). Active only after a second person approves (decision 11)';

CREATE TABLE supplier_item (
  id                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id           INT UNSIGNED NOT NULL,
  sku_id                INT UNSIGNED NOT NULL,
  supplier_code         VARCHAR(64)   NULL,
  supplier_description  VARCHAR(255)  NULL,
  purchase_unit         VARCHAR(32)   NOT NULL DEFAULT 'each',
  units_per_pack        INT UNSIGNED  NOT NULL DEFAULT 1 COMMENT 'central units in one purchase unit',
  moq_packs             INT UNSIGNED  NOT NULL DEFAULT 1,
  order_multiple_packs  INT UNSIGNED  NOT NULL DEFAULT 1,
  lead_days             TINYINT UNSIGNED NULL,
  is_preferred          TINYINT(1)    NOT NULL DEFAULT 0,
  is_active             TINYINT(1)    NOT NULL DEFAULT 1,
  preferred_sku_id      INT UNSIGNED GENERATED ALWAYS AS (IF(is_preferred = 1 AND is_active = 1, sku_id, NULL)) STORED,
  last_pack_price       DECIMAL(14,4) NULL COMMENT 'GBP excl. VAT per purchase unit: latest import/manual/invoice price, never a PO price',
  last_price_on         DATE          NULL,
  last_price_source     ENUM('import','manual','invoice') NULL,
  last_po_pack_price    DECIMAL(14,4) NULL,
  last_po_on            DATE          NULL,
  last_po_document_id   BIGINT UNSIGNED NULL,
  version               INT UNSIGNED  NOT NULL DEFAULT 1,
  created_by            INT UNSIGNED  NULL,
  created_actor         VARCHAR(64)   NOT NULL,
  created_at            DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_by            INT UNSIGNED  NULL,
  updated_actor         VARCHAR(64)   NOT NULL,
  updated_at            DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_item_pack (supplier_id, sku_id, units_per_pack),
  UNIQUE KEY uq_supplier_item_code (supplier_id, supplier_code),
  UNIQUE KEY uq_supplier_item_preferred (preferred_sku_id),
  KEY ix_supplier_item_sku (sku_id),
  KEY ix_supplier_item_po (last_po_document_id), KEY ix_supplier_item_created_by (created_by), KEY ix_supplier_item_updated_by (updated_by),
  CONSTRAINT fk_supplier_item_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id),
  CONSTRAINT fk_supplier_item_sku FOREIGN KEY (sku_id) REFERENCES sku (id),
  CONSTRAINT fk_supplier_item_po FOREIGN KEY (last_po_document_id) REFERENCES document (id),
  CONSTRAINT fk_supplier_item_created_by FOREIGN KEY (created_by) REFERENCES staff_user (id),
  CONSTRAINT fk_supplier_item_updated_by FOREIGN KEY (updated_by) REFERENCES staff_user (id),
  CONSTRAINT ck_supplier_item_pack CHECK (units_per_pack BETWEEN 1 AND 100000 AND moq_packs BETWEEN 1 AND 100000 AND order_multiple_packs BETWEEN 1 AND 10000),
  CONSTRAINT ck_supplier_item_flags CHECK (is_preferred IN (0,1) AND is_active IN (0,1)),
  CONSTRAINT ck_supplier_item_price CHECK (last_pack_price IS NULL OR last_pack_price >= 0),
  CONSTRAINT ck_supplier_item_last CHECK ((last_pack_price IS NULL) = (last_price_on IS NULL) AND (last_price_on IS NULL) = (last_price_source IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='what a supplier sells us: code, pack -> central units, MOQ, lead time, preferred, last price';

CREATE TABLE supplier_item_price (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_item_id  INT UNSIGNED NOT NULL,
  pack_price        DECIMAL(14,4) NOT NULL,
  units_per_pack    INT UNSIGNED  NOT NULL,
  unit_price        DECIMAL(14,6) NOT NULL COMMENT 'pack_price / units_per_pack (GBP per central unit, half-up)',
  source            ENUM('import','manual','po','invoice') NOT NULL,
  source_ref        VARCHAR(191)  NULL COMMENT 'ERPNext invoice no., PO number, import_run id',
  document_id       BIGINT UNSIGNED NULL,
  effective_on      DATE          NOT NULL,
  note              VARCHAR(255)  NULL,
  recorded_by       INT UNSIGNED  NULL,
  recorded_actor    VARCHAR(64)   NOT NULL,
  recorded_at       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY ix_supplier_item_price_item (supplier_item_id, effective_on, id),
  KEY ix_supplier_item_price_document (document_id), KEY ix_supplier_item_price_by (recorded_by),
  CONSTRAINT fk_supplier_item_price_item FOREIGN KEY (supplier_item_id) REFERENCES supplier_item (id),
  CONSTRAINT fk_supplier_item_price_document FOREIGN KEY (document_id) REFERENCES document (id),
  CONSTRAINT fk_supplier_item_price_by FOREIGN KEY (recorded_by) REFERENCES staff_user (id),
  CONSTRAINT ck_supplier_item_price_values CHECK (pack_price >= 0 AND units_per_pack >= 1 AND unit_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='price history (append-only for cw_app)';

CREATE TABLE import_run (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  kind           ENUM('erp_suppliers','erp_supplier_items','erp_open_pos') NOT NULL,
  file_name      VARCHAR(255) NOT NULL,
  file_sha256    CHAR(64)     NOT NULL,
  dry_run        TINYINT(1)   NOT NULL,
  status         ENUM('running','done','failed') NOT NULL DEFAULT 'running',
  rows_read      INT UNSIGNED NOT NULL DEFAULT 0,
  created        INT UNSIGNED NOT NULL DEFAULT 0,
  updated        INT UNSIGNED NOT NULL DEFAULT 0,
  skipped        INT UNSIGNED NOT NULL DEFAULT 0,
  failed         INT UNSIGNED NOT NULL DEFAULT 0,
  summary        JSON         NULL,
  actor          VARCHAR(64)  NOT NULL,
  staff_user_id  INT UNSIGNED NULL,
  started_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  finished_at    DATETIME(6)  NULL,
  PRIMARY KEY (id),
  KEY ix_import_run_file (kind, file_sha256),
  KEY ix_import_run_staff (staff_user_id),
  CONSTRAINT fk_import_run_staff FOREIGN KEY (staff_user_id) REFERENCES staff_user (id),
  CONSTRAINT ck_import_run_sha CHECK (REGEXP_LIKE(file_sha256, '^[0-9a-f]{64}$', 'c')),
  CONSTRAINT ck_import_run_flags CHECK (dry_run IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERPNext seed imports (backup copy only, decision 4)';
