<?php

declare(strict_types=1);

namespace CW\Matching;

/**
 * GENERATED by tools/first_match/build_flavour_vocab.php — do not edit by hand; re-run the tool instead.
 *
 * Seed flavour vocabulary from the Vape and Go export (pilot-1 fix 1; rule in Flavour::vocabularyFromSeed).
 * Canonical (stemmed) tokens that name a flavour on more seed products than they name a line or brand, and are
 * not already in Flavour::WORDS. PROPOSALS pending mapping-lead review, like every seed list here.
 */
final class FlavourVocab
{
    public const VERSION = 'fv1-aeaa0af8';

    public const SOURCE = [
        'file' => 'vapeandgo_listings_20260926T094152Z.jsonl.gz',
        'sha256' => 'aeaa0af84ac669ac59d79ba1a2cba0addba442bf6d055a4e36ddf18e223172f4',
        'seed_items' => 14856,
        'normalizer' => 'n2.0',
        'words' => 564,
    ];

    public const WORDS = [
        'adoni', 'airway', 'alive', 'amethyst', 'apollo', 'arctic', 'ardour', 'arthur', 'artic', 'ascot', 'ash',
        'athena', 'athene', 'atlanti', 'atomic', 'aura', 'autumn', 'bakery', 'bakewell', 'ball', 'bamboo',
        'bananariot', 'bang', 'bango', 'banilla', 'banoffee', 'banshee', 'barrel', 'batjuice', 'beach', 'bean',
        'beard', 'beast', 'belt', 'berg', 'berried', 'berrylicious', 'betty', 'bgum', 'billy', 'biscoff', 'bite',
        'blackberg', 'blackjack', 'blackpool', 'blazberry', 'blaze', 'blend', 'bliss', 'blitz', 'blonde', 'bluberry',
        'bluelicious', 'bluemonia', 'bluerazz', 'blueshift', 'bluez', 'blush', 'bomb', 'booky', 'boost', 'borea',
        'bossman', 'boston', 'boulevard', 'boundless', 'bread', 'bright', 'brilliant', 'bru', 'bruce', 'brummie',
        'bruu', 'bub', 'bubba', 'bubbla', 'bubblegun', 'bubblemint', 'bublegum', 'bueno', 'bugsy', 'bull', 'bullet',
        'buried', 'bursting', 'butter', 'cabin', 'cambell', 'camdem', 'cane', 'capone', 'captain', 'caramelised',
        'caribb', 'caribbean', 'carnival', 'castaway', 'catapult', 'cerberus', 'chang', 'chao', 'charlie', 'charm',
        'cheese', 'cherango', 'cherimoya', 'cherryfield', 'cherryfizz', 'chery', 'chew', 'chewit', 'chewriot',
        'chilled', 'chip', 'choco', 'chuckleberry', 'churchill', 'cigarette', 'cinnabird', 'claw', 'clementine',
        'clotted', 'cloud', 'cloudd', 'coastal', 'cobbler', 'coffe', 'colada', 'cold', 'collision', 'colombian',
        'colossal', 'comet', 'contra', 'coockie', 'cooky', 'copper', 'cosmo', 'country', 'craft', 'craze', 'crazy',
        'creme', 'crimson', 'crisp', 'crispy', 'crunch', 'cuban', 'cupcake', 'curly', 'curuba', 'cush', 'daiquiri',
        'death', 'deja', 'delicious', 'delight', 'delightful', 'deluxe', 'demon', 'devil', 'dew', 'dimpleberry',
        'doctar', 'doctor', 'dodger', 'dodoberry', 'dough', 'dread', 'dream', 'drgaon', 'drink', 'drizzle',
        'drumstick', 'dubai', 'dust', 'elder', 'elderpower', 'electroshock', 'elfbull', 'elfturbo', 'equinox',
        'espressino', 'evil', 'exotic', 'fairy', 'fantango', 'fantasia', 'fantasy', 'fcuking', 'fever', 'fiesta',
        'fitter', 'fizzle', 'flip', 'floss', 'flower', 'forrest', 'frappe', 'french', 'frenzy', 'fried', 'fruitti',
        'frutti', 'fudge', 'fuji', 'funky', 'fury', 'fusion', 'galaxy', 'gambino', 'gami', 'gangster', 'garden',
        'garrison', 'gazillion', 'godfella', 'goji', 'goodfella', 'granola', 'grapeberry', 'grappy', 'grenade',
        'guanabana', 'gummi', 'gun', 'gypsie', 'haden', 'havana', 'hawaii', 'hawaiian', 'hawthorn', 'heavenly',
        'heavy', 'heisen', 'heisenberg', 'heisenberry', 'heisengrape', 'heisenstrawberry', 'heizen', 'heizenberg',
        'highland', 'hilda', 'hippie', 'hizen', 'holiday', 'honeymoon', 'howler', 'hub', 'huba', 'hubba', 'hubbla',
        'hurdle', 'hustleberry', 'hydra', 'hyznberg', 'iceberg', 'iceland', 'iceolation', 'iceriot', 'island',
        'ivory', 'jack', 'jackfruit', 'jaffa', 'jamful', 'jammin', 'jammy', 'jeremiah', 'jewel', 'jogurt', 'journey',
        'juniper', 'kanzi', 'keewibera', 'khush', 'kick', 'killer', 'kiwiberry', 'kiwimelon', 'kool', 'kyoho', 'lace',
        'lagoon', 'leaf', 'legendary', 'lemonadenic', 'lilac', 'limoncello', 'lips', 'liqourice', 'lobotomy', 'loco',
        'lollipop', 'lolly', 'love', 'lucid', 'lunar', 'luscious', 'lush', 'mad', 'madame', 'madness', 'magic',
        'major', 'malevolent', 'malibu', 'malone', 'mamba', 'mangosteen', 'mania', 'maple', 'martini', 'marybull',
        'maryturbo', 'mcgavern', 'mcintosh', 'mecha', 'med', 'medley', 'melonade', 'melony', 'menthe', 'meringue',
        'metal', 'mexico', 'miami', 'mida', 'milky', 'million', 'mineral', 'minted', 'mintriot', 'minty', 'misty',
        'misu', 'miyako', 'monkberry', 'monkey', 'monster', 'moo', 'moon', 'morello', 'morning', 'mother', 'mountain',
        'mr', 'muffin', 'mulberry', 'mystic', 'neptune', 'nessie', 'nightshift', 'nola', 'nrg', 'nurse', 'oasi',
        'oatmeal', 'olive', 'opeium', 'ox', 'oxford', 'paan', 'palava', 'panther', 'paradise', 'parafait', 'parfait',
        'parma', 'pecanilla', 'pep', 'pikey', 'pina', 'pine', 'pinked', 'pinkerton', 'pinkman', 'pipeline',
        'pistachio', 'playa', 'plunder', 'pog', 'polly', 'poly', 'pom', 'pomegrante', 'pomelo', 'pool', 'pop',
        'popper', 'poppin', 'pressed', 'professor', 'psycho', 'pulsar', 'pumpkin', 'punchy', 'pynkman', 'queen',
        'raisin', 'rancher', 'rare', 'raspebrry', 'razapple', 'razor', 'razzriot', 'redshift', 'refresher',
        'refreshing', 'relentless', 'retro', 'riberry', 'rice', 'rich', 'rinbo', 'rio', 'ripple', 'rock', 'rocky',
        'rogue', 'roly', 'romance', 'royal', 'rubi', 'rush', 'sakura', 'salad', 'salmiak', 'salted', 'scone',
        'sebastian', 'sedative', 'selene', 'senorita', 'sensation', 'sex', 'shamrock', 'shattered', 'shellberg',
        'shellberry', 'sherbert', 'shiver', 'shortbread', 'shurb', 'sicilian', 'sicko', 'silly', 'sizzle', 'skitz',
        'skully', 'slammin', 'slice', 'slurpee', 'smashed', 'smooth', 'snicket', 'snoow', 'snowflake', 'softmint',
        'soloman', 'sorceress', 'sourade', 'sourberry', 'sourhead', 'spark', 'sparkling', 'speedster', 'spicy',
        'split', 'spread', 'spring', 'squash', 'squeeze', 'starburst', 'starbuzz', 'starfruit', 'stargazing',
        'starmix', 'starw', 'starwberry', 'sticky', 'straight', 'strawbery', 'strawbizzle', 'straweberry',
        'strawebrry', 'strawi', 'strawmelon', 'strawnana', 'strawzz', 'strudel', 'strudelmeister', 'sublime',
        'succulent', 'sugar', 'sukka', 'summer', 'sunrise', 'supernova', 'supersonic', 'surge', 'surgeon', 'sweety',
        'syrup', 'tahiti', 'tangy', 'tasty', 'tazz', 'tear', 'teeth', 'tequila', 'thunder', 'tiger', 'timber',
        'toast', 'toes', 'tommy', 'tooth', 'toxic', 'treasure', 'tropic', 'tru', 'truth', 'turkish', 'tutti',
        'twisted', 'typhon', 'unchained', 'unicorn', 'urban', 'valencia', 'valley', 'vamp', 'velvet', 'vendetta',
        'vera', 'vermillion', 'victorian', 'vim', 'vimade', 'vimbull', 'vimto', 'vimtonic', 'vimtru', 'vinberry',
        'virgina', 'virginia', 'vmt', 'volcano', 'voodoo', 'water', 'wateremelon', 'wave', 'whipped', 'wicked',
        'wing', 'winston', 'wish', 'witch', 'wong', 'worcester', 'worry', 'xtreme', 'zingberry',
    ];
}
